"""product master categories subcategories models

Revision ID: 2405b93c20fe
Revises: 514f0c48297c
Create Date: 2026-08-10

The product master, three levels deep: category → subcategory → model.

Company-scoped, unlike `regions` — geography is shared across tenants, a product
catalogue is not. `company_id` is denormalised onto subcategories and models so
a list query is one index probe instead of a two-level join.

Case-insensitive uniqueness is hand-written here rather than declared on the
model, because SQLAlchemy cannot express a functional index in a table
constraint. Each one is PARTIAL on `deleted_at IS NULL`: these rows are
soft-deleted (tickets reference them forever), and deleting a category must free
its name for reuse rather than poisoning it.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes and mistakes them for stale.
Those drops are intentionally absent.

No seed data here. The catalogue is per-company, so it is seeded by
`app/scripts/bootstrap.py`; migrations seed global reference data only.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2405b93c20fe'
down_revision: Union[str, Sequence[str], None] = '514f0c48297c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _audit_columns() -> list[sa.Column]:
    """IdMixin + AuditMixin + SoftDeleteMixin, spelled out once."""
    return [
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    ]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "product_categories",
        *_audit_columns(),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("icon_key", sa.String(length=32), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_product_categories_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categories")),
    )
    op.create_index(
        "ix_product_categories_company_id", "product_categories", ["company_id"]
    )

    op.create_table(
        "product_subcategories",
        *_audit_columns(),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        # Nullable: unset means "inherit the parent category's icon". This is
        # the level the technician app draws one tile per, so a Television and
        # an Air Conditioner under one category still get different glyphs.
        sa.Column("icon_key", sa.String(length=32), nullable=True),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_product_subcategories_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
            name=op.f("fk_product_subcategories_category_id_product_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_subcategories")),
    )
    op.create_index(
        "ix_product_subcategories_category_id",
        "product_subcategories",
        ["category_id"],
    )
    op.create_index(
        "ix_product_subcategories_company_id", "product_subcategories", ["company_id"]
    )

    op.create_table(
        "product_models",
        *_audit_columns(),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("subcategory_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_product_models_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["product_subcategories.id"],
            name=op.f("fk_product_models_subcategory_id_product_subcategories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_models")),
    )
    op.create_index(
        "ix_product_models_subcategory_id", "product_models", ["subcategory_id"]
    )
    op.create_index("ix_product_models_company_id", "product_models", ["company_id"])

    # Case-insensitive names, scoped to the parent, live rows only.
    op.execute(
        "CREATE UNIQUE INDEX uq_product_categories_company_name_lower "
        "ON product_categories (company_id, lower(name)) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_product_subcategories_category_name_lower "
        "ON product_subcategories (category_id, lower(name)) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_product_models_subcategory_name_lower "
        "ON product_models (subcategory_id, lower(name)) "
        "WHERE deleted_at IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS uq_product_models_subcategory_name_lower")
    op.execute("DROP INDEX IF EXISTS uq_product_subcategories_category_name_lower")
    op.execute("DROP INDEX IF EXISTS uq_product_categories_company_name_lower")

    op.drop_index("ix_product_models_company_id", table_name="product_models")
    op.drop_index("ix_product_models_subcategory_id", table_name="product_models")
    op.drop_table("product_models")

    op.drop_index(
        "ix_product_subcategories_company_id", table_name="product_subcategories"
    )
    op.drop_index(
        "ix_product_subcategories_category_id", table_name="product_subcategories"
    )
    op.drop_table("product_subcategories")

    op.drop_index("ix_product_categories_company_id", table_name="product_categories")
    op.drop_table("product_categories")
