"""push tokens - where to reach a technician when the app is closed

Revision ID: 25e087e3ce6e
Revises: b1c4e77a9d20
Create Date: 2026-08-26 15:07:13.631907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '25e087e3ce6e'
down_revision: Union[str, Sequence[str], None] = 'b1c4e77a9d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("platform IN ('android', 'ios')", name=op.f('ck_push_tokens_platform')),
    sa.ForeignKeyConstraint(['company_id', 'technician_id'], ['technician_profiles.company_id', 'technician_profiles.id'], name='fk_push_tokens_company_technician', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_push_tokens_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    sa.UniqueConstraint('token', name='uq_push_tokens_token')
    )
    op.create_index('ix_push_tokens_company_technician', 'push_tokens', ['company_id', 'technician_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_tokens_company_technician', table_name='push_tokens')
    op.drop_table('push_tokens')
    # ### end Alembic commands ###
