"""notifications, and who has read them

Two tables. One row per EVENT, scoped by pincode and resolved to an audience at
read time by the same rule that scopes tickets; read state per person in its
own table, because "has somebody read this" is not a question anybody asks.

Autogenerate's proposed drops of every hand-written functional and partial index
have been deleted, as in every migration before this.

Revision ID: 494d63571f2f
Revises: 19976ff14049
Create Date: 2026-08-25 16:07:19.884033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494d63571f2f'
down_revision: Union[str, Sequence[str], None] = '19976ff14049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('to', sa.String(length=255), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("kind IN ('escalation', 'ai', 'serial_mismatch', 'force_close', 'slot')", name=op.f('ck_notifications_kind')),
    sa.ForeignKeyConstraint(['company_id', 'ticket_id'], ['tickets.company_id', 'tickets.id'], name='fk_notifications_company_ticket', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_notifications_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_company_created', 'notifications', ['company_id', 'created_at'], unique=False)
    op.create_table('notification_reads',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_notification_reads_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_reads_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_reads')),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_reads')
    )
    op.create_index('ix_notification_reads_user', 'notification_reads', ['company_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_reads')
    op.drop_table('notifications')
    # ### end Alembic commands ###
