"""territory: regions, membership scope, territory.view feature

Revision ID: 89d57161b449
Revises: 9429173244b3
Create Date: 2026-08-08 18:52:05.723242

Adds the territory tables, seeds the five regions of India, and adds a
`territory.view` feature (default-on for admin and national_head) so the
territory page can be reached without handing out the whole settings bundle.

NB: the autogenerated diff wanted to DROP uq_companies_gst_lower,
uq_companies_slug_lower and uq_users_email_lower — Alembic does not recognise
hand-written LOWER() functional indexes and mistakes them for stale. Those drops
are intentionally removed here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d57161b449'
down_revision: Union[str, Sequence[str], None] = '9429173244b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (code, name, sort_order) — the five parts of India.
REGIONS = [
    ("NORTH", "North", 10),
    ("SOUTH", "South", 20),
    ("EAST", "East", 30),
    ("WEST", "West", 40),
    ("CENTRAL", "Central", 50),
]

FEATURE_KEY = "territory.view"
FEATURE_LABEL = "Territory"
FEATURE_SORT = 85  # between reports.view (80) and settings.view (90)
FEATURE_ROLES = ["admin", "national_head"]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('regions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('code', name=op.f('uq_regions_code'))
    )
    op.create_table('membership_pincodes',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_membership_pincodes_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_pincodes_membership_id_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_pincodes')),
    sa.UniqueConstraint('company_id', 'pincode', name='uq_company_pincode')
    )
    op.create_index('ix_membership_pincodes_membership_id', 'membership_pincodes', ['membership_id'], unique=False)
    op.create_table('membership_regions',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_regions_membership_id_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_membership_regions_region_id_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_regions')),
    sa.UniqueConstraint('membership_id', 'region_id', name='uq_membership_region')
    )
    op.create_index('ix_membership_regions_region_id', 'membership_regions', ['region_id'], unique=False)

    # ─── seeds ────────────────────────────────────────────────────────────
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO regions (code, name, sort_order) "
            "VALUES (:code, :name, :sort_order)"
        ),
        [{"code": c, "name": n, "sort_order": s} for (c, n, s) in REGIONS],
    )

    # The territory page needs its own feature: granting national_head
    # `settings.view` would also open Vendors, Categories and Rules Config.
    conn.execute(
        sa.text(
            "INSERT INTO features (key, label, sort_order) "
            "VALUES (:key, :label, :sort_order)"
        ),
        {"key": FEATURE_KEY, "label": FEATURE_LABEL, "sort_order": FEATURE_SORT},
    )
    # Bound per row: a parameter reused in both a SELECT list and a WHERE makes
    # Postgres report AmbiguousParameter, so each side is cast explicitly.
    for role in FEATURE_ROLES:
        conn.execute(
            sa.text(
                """
                INSERT INTO role_feature_defaults (role, feature_id, enabled)
                SELECT CAST(:role AS varchar), f.id, true
                FROM features f
                WHERE f.key = CAST(:key AS varchar)
                """
            ),
            {"role": role, "key": FEATURE_KEY},
        )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "DELETE FROM role_feature_defaults WHERE feature_id IN "
            "(SELECT id FROM features WHERE key = CAST(:key AS varchar))"
        ),
        {"key": FEATURE_KEY},
    )
    conn.execute(
        sa.text(
            "DELETE FROM company_role_features WHERE feature_id IN "
            "(SELECT id FROM features WHERE key = CAST(:key AS varchar))"
        ),
        {"key": FEATURE_KEY},
    )
    conn.execute(
        sa.text("DELETE FROM features WHERE key = CAST(:key AS varchar)"),
        {"key": FEATURE_KEY},
    )

    op.drop_index('ix_membership_regions_region_id', table_name='membership_regions')
    op.drop_table('membership_regions')
    op.drop_index('ix_membership_pincodes_membership_id', table_name='membership_pincodes')
    op.drop_table('membership_pincodes')
    op.drop_table('regions')
