"""initial schema

Revision ID: 9237a7143f8b
Revises:
Create Date: 2026-08-18

THE schema. One migration, replacing the twenty-two that grew the database from
empty to this — squashed because the audit columns had ended up first in half
the tables and last in the other half, and PostgreSQL has no
`ALTER TABLE ... REORDER`. Rebuilding was the only way to make them consistent,
and once you are rebuilding, twenty-two files of history for a product that has
not shipped is not worth keeping.

Audit columns come LAST in every table now, and that is enforced at the source
rather than here: the mixins in `app/db/mixins.py` use `declared_attr`, so they
are constructed after the model's own columns and sort behind them. Autogenerate
follows the models, so any table added from here on inherits the same order
without anyone having to remember a rule.

Two things autogenerate cannot produce, added by hand at the bottom:

  * functional and partial indexes — SQLAlchemy cannot express `lower(name)` or
    `WHERE deleted_at IS NULL` in an `Index()`. These are what make names
    case-insensitively unique while still freeing a name when a row is
    soft-deleted.
  * the global reference data — roles, regions, features and the per-role
    feature defaults. Not tenant data, and the platform does not work without
    it, so it ships with the schema rather than in a seed script.

Everything else, including all thirteen CHECK constraints, now lives on the
models, so `--autogenerate` can see the whole truth about every table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9237a7143f8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('gst_company_status', sa.String(length=64), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index('ix_companies_is_active', 'companies', ['is_active'], unique=False)
    op.create_table('features',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('parent_key', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_key'], ['features.key'], name=op.f('fk_features_parent_key_features'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features')),
    sa.UniqueConstraint('key', name=op.f('uq_features_key'))
    )
    op.create_table('regions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('code', name=op.f('uq_regions_code'))
    )
    op.create_table('roles',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_roles')),
    sa.UniqueConstraint('rank', name=op.f('uq_roles_rank'))
    )
    op.create_table('company_role_features',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_role_features_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_company_role_features_feature_id_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['roles.key'], name=op.f('fk_company_role_features_role_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_role_features')),
    sa.UniqueConstraint('company_id', 'role', 'feature_id', name='uq_company_role_feature')
    )
    op.create_index('ix_company_role_features_company_role', 'company_role_features', ['company_id', 'role'], unique=False)
    op.create_table('product_categories',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon_key', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_categories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('company_id', 'id', name='uq_product_categories_company_id_id')
    )
    op.create_index('ix_product_categories_company_id', 'product_categories', ['company_id'], unique=False)
    op.create_table('role_feature_defaults',
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_role_feature_defaults_feature_id_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['roles.key'], name=op.f('fk_role_feature_defaults_role_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_feature_defaults')),
    sa.UniqueConstraint('role', 'feature_id', name='uq_role_feature_default')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_active_company_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['last_active_company_id'], ['companies.id'], name=op.f('fk_users_last_active_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role'], ['roles.key'], name=op.f('fk_users_role_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('vendors',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('intake_channels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["Manual"]\'::jsonb'), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=False),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('jsonb_typeof(intake_channels) = \'array\' AND jsonb_array_length(intake_channels) >= 1 AND intake_channels <@ \'["API", "Excel", "Manual"]\'::jsonb', name=op.f('ck_vendors_intake_channels')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_vendors_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('company_id', 'id', name='uq_vendors_company_id_id')
    )
    op.create_index('ix_vendors_company_id', 'vendors', ['company_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_company_created', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'manager_id'], ['memberships.company_id', 'memberships.id'], name='fk_memberships_manager_same_company'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_memberships_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('company_id', 'id', name='uq_memberships_company_id_id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_memberships_user_company')
    )
    op.create_index('ix_memberships_company_created', 'memberships', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_memberships_company_id', 'memberships', ['company_id'], unique=False)
    op.create_table('product_subcategories',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon_key', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'category_id'], ['product_categories.company_id', 'product_categories.id'], name='fk_product_subcategories_company_category', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_subcategories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_subcategories')),
    sa.UniqueConstraint('company_id', 'id', name='uq_product_subcategories_company_id_id')
    )
    op.create_index('ix_product_subcategories_category_id', 'product_subcategories', ['category_id'], unique=False)
    op.create_index('ix_product_subcategories_company_id', 'product_subcategories', ['company_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('membership_pincodes',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_membership_pincodes_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_pincodes_membership_id_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_pincodes')),
    sa.UniqueConstraint('company_id', 'pincode', name='uq_company_pincode')
    )
    op.create_index('ix_membership_pincodes_membership_id', 'membership_pincodes', ['membership_id'], unique=False)
    op.create_table('membership_regions',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_regions_membership_id_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_membership_regions_region_id_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_regions')),
    sa.UniqueConstraint('membership_id', 'region_id', name='uq_membership_region')
    )
    op.create_index('ix_membership_regions_region_id', 'membership_regions', ['region_id'], unique=False)
    op.create_table('product_models',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('subcategory_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('service_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["Installation + Demo"]\'::jsonb'), nullable=False),
    sa.Column('capacity', sa.String(length=64), nullable=True),
    sa.Column('warranty_months', sa.SmallInteger(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('jsonb_typeof(service_types) = \'array\' AND jsonb_array_length(service_types) >= 1 AND service_types <@ \'["Installation + Demo", "Tech Visit", "Service"]\'::jsonb', name=op.f('ck_product_models_service_types')),
    sa.CheckConstraint('warranty_months IS NULL OR (warranty_months >= 0 AND warranty_months <= 240)', name=op.f('ck_product_models_warranty_months')),
    sa.ForeignKeyConstraint(['company_id', 'subcategory_id'], ['product_subcategories.company_id', 'product_subcategories.id'], name='fk_product_models_company_subcategory', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id', 'vendor_id'], ['vendors.company_id', 'vendors.id'], name='fk_product_models_company_vendor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_models_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_models')),
    sa.UniqueConstraint('company_id', 'id', name='uq_product_models_company_id_id')
    )
    op.create_index('ix_product_models_company_id', 'product_models', ['company_id'], unique=False)
    op.create_index('ix_product_models_subcategory_id', 'product_models', ['subcategory_id'], unique=False)
    op.create_index('ix_product_models_vendor_id', 'product_models', ['vendor_id'], unique=False)
    op.create_table('technician_invites',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('invited_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('manager_membership_id', sa.Uuid(), nullable=True),
    sa.Column('daily_job_cap', sa.SmallInteger(), server_default=sa.text('5'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('wa_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_user_id', sa.Uuid(), nullable=True),
    sa.Column('registered_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_technician_invites_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_membership_id'], ['memberships.id'], name=op.f('fk_technician_invites_invited_by_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_membership_id'], ['memberships.id'], name=op.f('fk_technician_invites_manager_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_technician_invites_region_id_regions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registered_membership_id'], ['memberships.id'], name=op.f('fk_technician_invites_registered_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], name=op.f('fk_technician_invites_registered_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technician_invites')),
    sa.UniqueConstraint('token', name=op.f('uq_technician_invites_token'))
    )
    op.create_index('ix_technician_invites_company_status', 'technician_invites', ['company_id', 'status'], unique=False)
    op.create_index('ix_technician_invites_region_id', 'technician_invites', ['region_id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('invite_id', sa.Uuid(), nullable=True),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_channel', sa.String(length=16), nullable=True),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('wa_error', sa.Text(), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("purpose IN ('login','invite')", name=op.f('ck_otp_codes_purpose')),
    sa.ForeignKeyConstraint(['invite_id'], ['technician_invites.id'], name=op.f('fk_otp_codes_invite_id_technician_invites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index('ix_otp_codes_ip_created', 'otp_codes', ['request_ip', 'created_at'], unique=False)
    op.create_index('ix_otp_codes_phone_created', 'otp_codes', ['phone', 'created_at'], unique=False)
    op.create_index('ix_otp_codes_purpose_phone', 'otp_codes', ['purpose', 'phone'], unique=False)
    op.create_table('technician_profiles',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('daily_job_cap', sa.SmallInteger(), server_default=sa.text('5'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('onboarding_mode', sa.String(length=16), nullable=False),
    sa.Column('appointed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('appointed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('appointed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('registered_by', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invite_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_cancelled', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('on_time_pct', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("onboarding_mode IN ('invite','direct')", name=op.f('ck_technician_profiles_onboarding_mode')),
    sa.CheckConstraint("registered_by IN ('self','manager')", name=op.f('ck_technician_profiles_registered_by')),
    sa.CheckConstraint("status IN ('active','inactive','suspended')", name=op.f('ck_technician_profiles_status')),
    sa.CheckConstraint('daily_job_cap BETWEEN 1 AND 12', name=op.f('ck_technician_profiles_daily_job_cap')),
    sa.ForeignKeyConstraint(['appointed_by_membership_id'], ['memberships.id'], name=op.f('fk_technician_profiles_appointed_by_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id', 'membership_id'], ['memberships.company_id', 'memberships.id'], name='fk_technician_profiles_company_membership', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_technician_profiles_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_id'], ['technician_invites.id'], name=op.f('fk_technician_profiles_invite_id_technician_invites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_technician_profiles_region_id_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technician_profiles')),
    sa.UniqueConstraint('company_id', 'code', name='uq_technician_profiles_company_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_technician_profiles_company_id_id'),
    sa.UniqueConstraint('membership_id', name='uq_technician_profiles_membership')
    )
    op.create_index('ix_technician_profiles_appointed_by', 'technician_profiles', ['appointed_by_user_id'], unique=False)
    op.create_index('ix_technician_profiles_company_status', 'technician_profiles', ['company_id', 'status'], unique=False)
    op.create_index('ix_technician_profiles_region_id', 'technician_profiles', ['region_id'], unique=False)
    op.create_table('technician_pincodes',
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'technician_id'], ['technician_profiles.company_id', 'technician_profiles.id'], name='fk_technician_pincodes_company_technician', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_technician_pincodes_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technician_pincodes')),
    sa.UniqueConstraint('technician_id', 'pincode', name='uq_technician_pincode')
    )
    op.create_index('ix_technician_pincodes_company_pincode', 'technician_pincodes', ['company_id', 'pincode'], unique=False)
    op.create_table('technician_subcategories',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('subcategory_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'subcategory_id'], ['product_subcategories.company_id', 'product_subcategories.id'], name='fk_technician_subcategories_company_subcategory', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'technician_id'], ['technician_profiles.company_id', 'technician_profiles.id'], name='fk_technician_subcategories_company_technician', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_technician_subcategories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technician_subcategories')),
    sa.UniqueConstraint('technician_id', 'subcategory_id', name='uq_technician_subcategory')
    )
    op.create_index('ix_technician_subcategories_subcategory_id', 'technician_subcategories', ['subcategory_id'], unique=False)
    op.create_table('tickets',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('subcategory_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('service_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('service_level_hours', sa.SmallInteger(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_token', sa.String(length=64), nullable=True),
    sa.Column('slot_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slot_request_status', sa.String(length=16), server_default=sa.text("'not_needed'"), nullable=False),
    sa.Column('slot_request_error', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("service_type IN ('Installation + Demo', 'Tech Visit', 'Service')", name=op.f('ck_tickets_service_type')),
    sa.CheckConstraint("slot_request_status IN ('not_needed', 'pending', 'sent', 'failed')", name=op.f('ck_tickets_slot_request_status')),
    sa.CheckConstraint("status IN ('New', 'Slot Pending', 'Assigned', 'In Progress', 'AI Review', 'Escalated', 'Closed', 'Force-Closed', 'Cancelled')", name=op.f('ck_tickets_status')),
    sa.CheckConstraint('(slot_start IS NULL) = (slot_end IS NULL) AND (slot_end IS NULL OR slot_end > slot_start)', name=op.f('ck_tickets_slot_both_or_neither')),
    sa.CheckConstraint('service_level_hours IN (12, 24, 36, 48)', name=op.f('ck_tickets_service_level_hours')),
    sa.ForeignKeyConstraint(['company_id', 'model_id'], ['product_models.company_id', 'product_models.id'], name='fk_tickets_company_model', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'subcategory_id'], ['product_subcategories.company_id', 'product_subcategories.id'], name='fk_tickets_company_subcategory', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'technician_id'], ['technician_profiles.company_id', 'technician_profiles.id'], name='fk_tickets_company_technician', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'vendor_id'], ['vendors.company_id', 'vendors.id'], name='fk_tickets_company_vendor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_tickets_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('company_id', 'code', name='uq_tickets_company_code')
    )
    op.create_index('ix_tickets_company_pincode', 'tickets', ['company_id', 'pincode'], unique=False)
    op.create_index('ix_tickets_company_sla_due_at', 'tickets', ['company_id', 'sla_due_at'], unique=False)
    op.create_index('ix_tickets_company_status', 'tickets', ['company_id', 'status'], unique=False)
    op.create_index('ix_tickets_technician_id', 'tickets', ['technician_id'], unique=False)


    # -- indexes SQLAlchemy cannot express -------------------------------
    #
    # Case-insensitive uniqueness, and mostly PARTIAL on `deleted_at IS NULL` so
    # removing a row frees its name for reuse rather than poisoning it.
    # `Index()` can say neither half of that, so these are raw DDL — and the
    # reason the autogenerated diff always wants to DROP them is that Alembic
    # cannot see them either. Never accept that drop.
    #
    # NB the first three below are NOT partial as written here. That was the
    # bug `4c8f1b7d2e93` fixes; it is left as-is rather than rewritten, because
    # editing an applied migration makes a fresh database and an existing one
    # disagree about what has run.
    op.execute(
        "CREATE UNIQUE INDEX uq_companies_slug_lower ON companies (lower(slug))"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_companies_gst_lower ON companies (lower(gst_number))"
    )
    op.execute("CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email))")
    # A technician's phone IS their identity, so it is unique among technicians
    # only, and only while they exist — a removed number can be re-onboarded.
    op.execute(
        "CREATE UNIQUE INDEX uq_users_phone_technician ON users (phone) "
        "WHERE role = 'technician' AND phone IS NOT NULL AND deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_product_categories_company_name_lower "
        "ON product_categories (company_id, lower(name)) WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_product_subcategories_category_name_lower "
        "ON product_subcategories (category_id, lower(name)) WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_product_models_subcategory_name_lower "
        "ON product_models (subcategory_id, lower(name)) WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_vendors_company_name_lower "
        "ON vendors (company_id, lower(name)) WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_vendors_company_gst_lower "
        "ON vendors (company_id, lower(gst_number)) WHERE deleted_at IS NULL"
    )
    # Positive predicate on purpose: cancelled, expired AND registered numbers
    # must all be re-invitable, so only the live states are constrained.
    op.execute(
        "CREATE UNIQUE INDEX uq_technician_invites_company_phone_live "
        "ON technician_invites (company_id, phone) "
        "WHERE status IN ('pending', 'sent', 'failed')"
    )
    # The token IS the URL, so it is unique platform-wide, and only the tickets
    # that actually asked the customer carry one.
    op.execute(
        "CREATE UNIQUE INDEX uq_tickets_slot_token "
        "ON tickets (slot_token) WHERE slot_token IS NOT NULL"
    )
    # GIN, because both are filtered by containment: "which vendors take Excel",
    # "which models support a Tech Visit".
    op.execute(
        "CREATE INDEX ix_vendors_intake_channels ON vendors USING GIN (intake_channels)"
    )
    op.execute(
        "CREATE INDEX ix_product_models_service_types "
        "ON product_models USING GIN (service_types)"
    )

    _seed_reference_data()


# -- global reference data ------------------------------------------------
#
# Not tenant data — one catalogue for the whole platform, and nothing works
# without it: no roles and nobody can be created, no features and every endpoint
# 403s. So it ships with the schema rather than in a seed script.

ROLES = [
    ("superadmin", "Super Admin", 0),
    ("admin", "Admin", 1),
    ("national_head", "National Head", 2),
    ("regional_head", "Regional Head", 3),
    ("area_manager", "Area Manager", 4),
    ("technician", "Technician", 5),
]

REGIONS = [
    ("NORTH", "North", 10),
    ("SOUTH", "South", 20),
    ("EAST", "East", 30),
    ("WEST", "West", 40),
    ("CENTRAL", "Central", 50),
]

# (key, label, parent_key, sort_order) — parents before children, because
# `features.parent_key` is a self-referencing foreign key.
FEATURES = [
    ("dashboard.view", "Dashboard", None, 10),
    ("users.view", "Users", None, 20),
    ("users.create", "Create User", "users.view", 21),
    ("users.edit", "Edit User", "users.view", 22),
    ("users.delete", "Delete User", "users.view", 23),
    ("roles.view", "Roles", None, 30),
    ("features.manage", "Feature Access", None, 31),
    ("jobs.view", "Jobs", None, 40),
    ("jobs.create", "Create Job", "jobs.view", 41),
    ("jobs.assign", "Assign Job", "jobs.view", 42),
    ("jobs.close", "Close Job", "jobs.view", 43),
    ("pool.view", "Job Pool", None, 50),
    ("technicians.view", "Technicians", None, 60),
    ("technicians.create", "Onboard Technician", "technicians.view", 61),
    ("technicians.invite", "Invite Technician", "technicians.view", 62),
    ("technicians.edit", "Edit Technician", "technicians.view", 63),
    ("earnings.view", "Earnings", None, 70),
    ("reports.view", "Reports", None, 80),
    ("masters.view", "Product Master", None, 85),
    ("masters.edit", "Edit Product Master", "masters.view", 86),
    ("territory.view", "Territory", None, 87),
    ("vendors.view", "Vendors", None, 88),
    ("vendors.edit", "Edit Vendors", "vendors.view", 89),
    ("settings.view", "Settings", None, 90),
]

# What each role can do out of the box. A company overrides any of it in
# `company_role_features`; superadmin appears nowhere because it is a platform
# role whose feature set is a fixed list in code, not a table.
#
# vendors.* is admin and national_head only. The router enforces a rank floor on
# top of the feature, so a per-company override cannot hand it further down.
DEFAULTS = {
    "admin": [k for k, _, _, _ in FEATURES],
    "national_head": [
        "dashboard.view", "earnings.view", "jobs.assign", "jobs.create",
        "jobs.view", "masters.edit", "masters.view", "pool.view",
        "reports.view", "roles.view", "settings.view", "technicians.create",
        "technicians.edit", "technicians.invite", "technicians.view",
        "territory.view", "users.create", "users.edit", "users.view",
        "vendors.edit", "vendors.view",
    ],
    "regional_head": [
        "dashboard.view", "jobs.assign", "jobs.create", "jobs.view",
        "masters.view", "pool.view", "reports.view", "technicians.create",
        "technicians.edit", "technicians.invite", "technicians.view",
        "territory.view", "users.create", "users.view",
    ],
    "area_manager": [
        "dashboard.view", "jobs.assign", "jobs.create", "jobs.view",
        "masters.view", "pool.view", "technicians.create", "technicians.edit",
        "technicians.invite", "technicians.view",
    ],
    "technician": ["dashboard.view", "jobs.close", "jobs.view", "pool.view"],
}


def _seed_reference_data() -> None:
    conn = op.get_bind()
    conn.execute(
        sa.text("INSERT INTO roles (key, label, rank) VALUES (:k, :l, :r)"),
        [{"k": k, "l": lbl, "r": r} for k, lbl, r in ROLES],
    )
    conn.execute(
        sa.text(
            "INSERT INTO regions (code, name, sort_order, is_active) "
            "VALUES (:c, :n, :s, true)"
        ),
        [{"c": c, "n": n, "s": s} for c, n, s in REGIONS],
    )
    conn.execute(
        sa.text(
            "INSERT INTO features (key, label, parent_key, sort_order, is_active) "
            "VALUES (:k, :l, :p, :s, true)"
        ),
        [{"k": k, "l": lbl, "p": p, "s": s} for k, lbl, p, s in FEATURES],
    )
    conn.execute(
        sa.text(
            "INSERT INTO role_feature_defaults (role, feature_id, enabled) "
            "SELECT :role, f.id, true FROM features f WHERE f.key = :key"
        ),
        [
            {"role": role, "key": key}
            for role, keys in DEFAULTS.items()
            for key in keys
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_technician_id', table_name='tickets')
    op.drop_index('ix_tickets_company_status', table_name='tickets')
    op.drop_index('ix_tickets_company_sla_due_at', table_name='tickets')
    op.drop_index('ix_tickets_company_pincode', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_technician_subcategories_subcategory_id', table_name='technician_subcategories')
    op.drop_table('technician_subcategories')
    op.drop_index('ix_technician_pincodes_company_pincode', table_name='technician_pincodes')
    op.drop_table('technician_pincodes')
    op.drop_index('ix_technician_profiles_region_id', table_name='technician_profiles')
    op.drop_index('ix_technician_profiles_company_status', table_name='technician_profiles')
    op.drop_index('ix_technician_profiles_appointed_by', table_name='technician_profiles')
    op.drop_table('technician_profiles')
    op.drop_index('ix_otp_codes_purpose_phone', table_name='otp_codes')
    op.drop_index('ix_otp_codes_phone_created', table_name='otp_codes')
    op.drop_index('ix_otp_codes_ip_created', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index('ix_technician_invites_region_id', table_name='technician_invites')
    op.drop_index('ix_technician_invites_company_status', table_name='technician_invites')
    op.drop_table('technician_invites')
    op.drop_index('ix_product_models_vendor_id', table_name='product_models')
    op.drop_index('ix_product_models_subcategory_id', table_name='product_models')
    op.drop_index('ix_product_models_company_id', table_name='product_models')
    op.drop_table('product_models')
    op.drop_index('ix_membership_regions_region_id', table_name='membership_regions')
    op.drop_table('membership_regions')
    op.drop_index('ix_membership_pincodes_membership_id', table_name='membership_pincodes')
    op.drop_table('membership_pincodes')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_product_subcategories_company_id', table_name='product_subcategories')
    op.drop_index('ix_product_subcategories_category_id', table_name='product_subcategories')
    op.drop_table('product_subcategories')
    op.drop_index('ix_memberships_company_id', table_name='memberships')
    op.drop_index('ix_memberships_company_created', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_audit_logs_company_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_vendors_company_id', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('role_feature_defaults')
    op.drop_index('ix_product_categories_company_id', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index('ix_company_role_features_company_role', table_name='company_role_features')
    op.drop_table('company_role_features')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('features')
    op.drop_index('ix_companies_is_active', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
