"""company statutory fields: gstin, pan, address, gst status

Revision ID: 9429173244b3
Revises: ab9aa7e44f00
Create Date: 2026-08-06 18:00:53.620115

Adds statutory identity columns to companies. NOT NULL is safe: the table is
empty (fresh DBs create it empty before this alter runs), so no backfill.

NB: the autogenerated diff wanted to DROP uq_companies_slug_lower and
uq_users_email_lower — Alembic does not recognise hand-written LOWER() functional
indexes and mistakes them for stale. Those drops are intentionally removed here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9429173244b3'
down_revision: Union[str, Sequence[str], None] = 'ab9aa7e44f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('companies', sa.Column('gst_number', sa.String(length=15), nullable=False))
    op.add_column('companies', sa.Column('pan', sa.String(length=10), nullable=False))
    op.add_column('companies', sa.Column('gst_company_status', sa.String(length=64), nullable=False))
    op.add_column('companies', sa.Column('address_line1', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('companies', sa.Column('state', sa.String(length=120), nullable=False))
    op.add_column('companies', sa.Column('pincode', sa.String(length=10), nullable=False))

    # Case-insensitive uniqueness on GSTIN (functional index — not autogenerated).
    op.create_index(
        'uq_companies_gst_lower', 'companies', [sa.text('lower(gst_number)')], unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_companies_gst_lower', table_name='companies')
    op.drop_column('companies', 'pincode')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'address_line2')
    op.drop_column('companies', 'address_line1')
    op.drop_column('companies', 'gst_company_status')
    op.drop_column('companies', 'pan')
    op.drop_column('companies', 'gst_number')
