"""vendor intake channels

Revision ID: a7f31c8b2e45
Revises: f4d2c9a15b67
Create Date: 2026-08-18

How a vendor's tickets reach us — §4 of the requirement document: API, Excel
upload, or manual entry. A vendor may hold SEVERAL at once, so this is a list
rather than a single value: the same company can send a spreadsheet on Monday
and have ops key an urgent one in on Tuesday.

JSONB rather than a child table, for the same reason as `product_models.
image_urls`: the list is bounded at three, always read whole with its vendor,
and never queried on its own — a join would buy nothing and cost a second
composite-FK relationship to keep tenant-safe.

Two rules, split on purpose between here and the schema layer:

  * WHAT MAY EXIST is a CHECK, because the three channels are fixed by the
    requirement document and will not move. (Contrast `icon_key`, validated only
    in the schema layer: that catalogue changes with a deploy, and a CHECK there
    would make adding an icon a migration.)
  * WHAT MAY BE SELECTED lives in `app/core/intake.py`. "API" is a valid stored
    value but is not offered yet — nothing exists for a vendor's system to push
    to, and no key for it to authenticate with. When that ships it is a one-word
    change with no migration.

Non-destructive. Existing vendors take the `["Manual"]` default, which is the
honest value: nobody has configured anything else, and somebody can always type
a ticket in.

A GIN index because the console filters the list by channel, and containment
(`intake_channels @> '["Excel"]'`) is what that filter compiles to.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes and mistakes them for stale.
Those drops are intentionally absent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'a7f31c8b2e45'
down_revision: Union[str, Sequence[str], None] = 'f4d2c9a15b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "vendors",
        sa.Column(
            "intake_channels",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[\"Manual\"]'::jsonb"),
        ),
    )

    # An array, holding at least one value, drawn only from the closed set.
    # `<@` is containment the other way round: every element of the left must
    # appear in the right.
    op.create_check_constraint(
        "ck_vendors_intake_channels",
        "vendors",
        "jsonb_typeof(intake_channels) = 'array' "
        "AND jsonb_array_length(intake_channels) >= 1 "
        "AND intake_channels <@ '[\"API\", \"Excel\", \"Manual\"]'::jsonb",
    )

    op.execute(
        "CREATE INDEX ix_vendors_intake_channels "
        "ON vendors USING GIN (intake_channels)"
    )


def downgrade() -> None:
    """Downgrade schema.

    Lossy, but only of a setting: which channels each vendor was marked with is
    gone, and re-upgrading puts everyone back on the Manual default.
    """
    op.execute("DROP INDEX IF EXISTS ix_vendors_intake_channels")
    op.drop_constraint("ck_vendors_intake_channels", "vendors", type_="check")
    op.drop_column("vendors", "intake_channels")
