"""technician invites profiles certifications coverage

Revision ID: a9c9817495b0
Revises: ef3a0a02c5c3
Create Date: 2026-08-10

The technician side of onboarding: an invite, the profile it becomes, and the
two lists a job offer matches on.

Order matters — `technician_profiles.invite_id` references `technician_invites`,
so invites are created first. There is no cycle: invites reference only
companies, regions, memberships and users.

`technician_pincodes` is deliberately NOT unique on (company_id, pincode). That
constraint lives on `membership_pincodes`, where it enforces "a pincode belongs
to exactly one area manager". Technician coverage is the opposite rule — many
technicians serve one pincode and share it with their ASM — which is exactly why
this is a separate table rather than a reuse.

The live-invite unique index uses a POSITIVE predicate rather than
`<> 'cancelled'`: cancelled, expired AND already-registered numbers must all be
re-invitable, and only the first of those is excluded by a negative test.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes. Those drops are absent here
on purpose.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9c9817495b0'
down_revision: Union[str, Sequence[str], None] = 'ef3a0a02c5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _audit_columns() -> list[sa.Column]:
    """IdMixin + AuditMixin. These tables are not soft-deleted."""
    return [
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
    ]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "technician_invites",
        *_audit_columns(),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        # No FK: the manager may leave the company and the historical fact of
        # who appointed this technician has to survive that.
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("invited_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("manager_membership_id", sa.Uuid(), nullable=True),
        sa.Column(
            "daily_job_cap",
            sa.SmallInteger(),
            server_default=sa.text("5"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wa_message_id", sa.String(length=128), nullable=True),
        sa.Column("wa_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "send_attempts",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registered_user_id", sa.Uuid(), nullable=True),
        sa.Column("registered_membership_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_technician_invites_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_technician_invites_region_id_regions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_technician_invites_invited_by_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["manager_membership_id"],
            ["memberships.id"],
            name=op.f("fk_technician_invites_manager_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["registered_user_id"],
            ["users.id"],
            name=op.f("fk_technician_invites_registered_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["registered_membership_id"],
            ["memberships.id"],
            name=op.f("fk_technician_invites_registered_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_invites")),
        sa.UniqueConstraint("token", name=op.f("uq_technician_invites_token")),
    )
    op.create_index(
        "ix_technician_invites_company_status",
        "technician_invites",
        ["company_id", "status"],
    )
    op.create_index(
        "ix_technician_invites_region_id", "technician_invites", ["region_id"]
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_technician_invites_company_phone_live "
        "ON technician_invites (company_id, phone) "
        "WHERE status IN ('pending','sent','failed')"
    )

    op.create_table(
        "technician_profiles",
        *_audit_columns(),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column(
            "daily_job_cap",
            sa.SmallInteger(),
            server_default=sa.text("5"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("onboarding_mode", sa.String(length=16), nullable=False),
        sa.Column("appointed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("appointed_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column(
            "appointed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("registered_by", sa.String(length=16), nullable=False),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invite_id", sa.Uuid(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "jobs_completed", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "jobs_cancelled", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("on_time_pct", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_technician_profiles_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_technician_profiles_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_technician_profiles_region_id_regions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["appointed_by_membership_id"],
            ["memberships.id"],
            name=op.f("fk_technician_profiles_appointed_by_membership_id_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["technician_invites.id"],
            name=op.f("fk_technician_profiles_invite_id_technician_invites"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_profiles")),
        sa.UniqueConstraint("membership_id", name="uq_technician_profiles_membership"),
        sa.UniqueConstraint(
            "company_id", "code", name="uq_technician_profiles_company_code"
        ),
        sa.CheckConstraint(
            "daily_job_cap BETWEEN 1 AND 12",
            name="ck_technician_profiles_daily_job_cap",
        ),
        sa.CheckConstraint(
            "onboarding_mode IN ('invite','direct')",
            name="ck_technician_profiles_onboarding_mode",
        ),
        sa.CheckConstraint(
            "registered_by IN ('self','manager')",
            name="ck_technician_profiles_registered_by",
        ),
        sa.CheckConstraint(
            "status IN ('active','inactive','suspended')",
            name="ck_technician_profiles_status",
        ),
    )
    op.create_index(
        "ix_technician_profiles_company_status",
        "technician_profiles",
        ["company_id", "status"],
    )
    op.create_index(
        "ix_technician_profiles_region_id", "technician_profiles", ["region_id"]
    )
    op.create_index(
        "ix_technician_profiles_appointed_by",
        "technician_profiles",
        ["appointed_by_user_id"],
    )

    op.create_table(
        "technician_subcategories",
        *_audit_columns(),
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("subcategory_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technician_profiles.id"],
            name=op.f("fk_technician_subcategories_technician_id_technician_profiles"),
            ondelete="CASCADE",
        ),
        # RESTRICT, not CASCADE: removing a subcategory somebody is certified
        # for must be refused with a message, not silently decertify them.
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["product_subcategories.id"],
            name=op.f(
                "fk_technician_subcategories_subcategory_id_product_subcategories"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_subcategories")),
        sa.UniqueConstraint(
            "technician_id", "subcategory_id", name="uq_technician_subcategory"
        ),
    )
    op.create_index(
        "ix_technician_subcategories_subcategory_id",
        "technician_subcategories",
        ["subcategory_id"],
    )

    op.create_table(
        "technician_pincodes",
        *_audit_columns(),
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("pincode", sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technician_profiles.id"],
            name=op.f("fk_technician_pincodes_technician_id_technician_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_technician_pincodes_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_pincodes")),
        sa.UniqueConstraint("technician_id", "pincode", name="uq_technician_pincode"),
    )
    # The routing lookup: "who covers 400067 in this company". NOT unique.
    op.create_index(
        "ix_technician_pincodes_company_pincode",
        "technician_pincodes",
        ["company_id", "pincode"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "ix_technician_pincodes_company_pincode", table_name="technician_pincodes"
    )
    op.drop_table("technician_pincodes")

    op.drop_index(
        "ix_technician_subcategories_subcategory_id",
        table_name="technician_subcategories",
    )
    op.drop_table("technician_subcategories")

    op.drop_index(
        "ix_technician_profiles_appointed_by", table_name="technician_profiles"
    )
    op.drop_index("ix_technician_profiles_region_id", table_name="technician_profiles")
    op.drop_index(
        "ix_technician_profiles_company_status", table_name="technician_profiles"
    )
    op.drop_table("technician_profiles")

    op.execute("DROP INDEX IF EXISTS uq_technician_invites_company_phone_live")
    op.drop_index("ix_technician_invites_region_id", table_name="technician_invites")
    op.drop_index(
        "ix_technician_invites_company_status", table_name="technician_invites"
    )
    op.drop_table("technician_invites")
