"""Model-wise serial numbers

A serial has only ever been an INSTANCE fact here. `tickets.serial_number` is
the number a vendor reads off the invoice at intake, mandatory since vendors
started raising their own tickets — but nothing in the master could say whether
it was a plausible serial for the model being ticketed. A television's number
raised against an air conditioner stored happily, and the first anybody knew was
a `serial_mismatch` raised with a technician already standing at the customer's
door.

This adds the missing master data: the set of serial numbers each product model
is known to cover. `tickets._resolve_product` checks the typed serial against it
before the ticket exists.

## Empty means UNCHECKED

The table is created EMPTY and there is deliberately no backfill, because there
is no honest source for one — the same shape `f4b28d1a67c3` reached for when a
company phone had no derivable default, except that here the answer is better
than refusing to run: `_assert_serial_known` refuses a serial only when the
model has at least one row here, so a model nobody has loaded is simply not
checked. That is what lets this ship against a live catalogue with no flag day.
A company loads its models one at a time instead of every vendor's intake
breaking on deploy.

## The UNIQUE is hand-written, and autogenerate will want to drop it

`(company_id, product_model_id, lower(serial))` is a functional index, and
Alembic does not recognise `LOWER()` — it mistakes them for stale and emits a
drop on every run. `uq_product_models_node_name_lower`, `uq_companies_gst_lower`
and `uq_users_email_lower` are all spelled this way and all have to be deleted
out of autogenerated revisions by hand. This one joins them.

Total rather than partial, unlike its three siblings: `product_model_serials`
has no `deleted_at`, so the soft-delete rule that makes every other UNIQUE in
the product master partial does not apply here.

Case-insensitive because `jobs.service.serial_mismatch` already compares the
photographed serial trimmed and lower-cased. Two rules disagreeing about case
would be worse than one.

Revision ID: b5e9c412d80a
Revises: d6a1f38b04e5
Create Date: 2026-09-07

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5e9c412d80a"
down_revision: Union[str, Sequence[str], None] = "d6a1f38b04e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "product_model_serials",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("product_model_id", sa.Uuid(), nullable=False),
        sa.Column("serial", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], ondelete="CASCADE"
        ),
        # COMPOSITE, pointing at `uq_product_models_company_id_id`. A plain
        # `product_model_id` FK would let company A's serials hang off company
        # B's model — the database would store it, and only an application
        # check would stand in the way.
        sa.ForeignKeyConstraint(
            ["company_id", "product_model_id"],
            ["product_models.company_id", "product_models.id"],
            name="fk_product_model_serials_company_model",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Covering index for the composite FK, columns IN ORDER. Postgres creates
    # none, and the cost lands twice: every lookup by model scans, and so does
    # every DELETE of a model, because the database must prove no serial still
    # references it. An index on `company_id` alone would not serve this.
    op.create_index(
        "ix_product_model_serials_company_model",
        "product_model_serials",
        ["company_id", "product_model_id"],
    )
    # Hand-written: see the module docstring. Scoped to the MODEL rather than
    # the company — a serial physically names one unit, so company-wide
    # uniqueness is tempting, but it is a stronger claim than the intake check
    # needs and would reject a legitimate import where two models genuinely
    # share a numbering scheme.
    op.execute(
        "CREATE UNIQUE INDEX uq_product_model_serials_model_serial_lower "
        "ON product_model_serials (company_id, product_model_id, lower(serial))"
    )


def downgrade() -> None:
    # The serials themselves go with the table. Unlike `c4e81b90f7a2`, which
    # guards its downgrade because dropping approval columns would lose
    # decisions nobody could reconstruct, there is nothing to protect here: the
    # rows are a re-uploadable copy of what is written on the units, and the
    # spreadsheet they came from is the source.
    op.execute("DROP INDEX IF EXISTS uq_product_model_serials_model_serial_lower")
    op.drop_index(
        "ix_product_model_serials_company_model",
        table_name="product_model_serials",
    )
    op.drop_table("product_model_serials")
