"""product model service types

Revision ID: b8e42a6d1f07
Revises: a7f31c8b2e45
Create Date: 2026-08-18

What a technician can be sent to do with a product model: Installation + Demo,
Tech Visit, Service. A model declares which it supports, and that is what a
ticket raised against it will be allowed to ask for.

Several at once, because most models support more than one: a washing machine
is installed and demonstrated, and later serviced. So a list, like
`vendors.intake_channels` and for the same reasons — bounded at three, always
read whole with its model, never queried on its own, so JSONB rather than a
child table that would cost another composite-FK relationship to keep
tenant-safe.

Membership and "at least one" are a CHECK here, not only a schema-layer rule.
Contrast `icon_key`, which is validated in the schema layer alone because that
catalogue changes with a deploy and a CHECK would make adding an icon a
migration. These three are the shapes of work the business does; they do not
move on a release cadence.

Non-destructive. Existing models take `["Installation + Demo"]`, which is the
honest default rather than a guess: this product exists for installation and
demo work, and every seeded model is exactly that.

A GIN index because ticket intake will ask "which models support a Tech Visit",
and containment is what that question compiles to.

The ticket side is deliberately NOT wired in this revision. The model records
what it supports first; intake reads it when the jobs slice lands.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes and mistakes them for stale.
Those drops are intentionally absent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b8e42a6d1f07'
down_revision: Union[str, Sequence[str], None] = 'a7f31c8b2e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "product_models",
        sa.Column(
            "service_types",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[\"Installation + Demo\"]'::jsonb"),
        ),
    )

    op.create_check_constraint(
        "ck_product_models_service_types",
        "product_models",
        "jsonb_typeof(service_types) = 'array' "
        "AND jsonb_array_length(service_types) >= 1 "
        "AND service_types <@ "
        "'[\"Installation + Demo\", \"Tech Visit\", \"Service\"]'::jsonb",
    )

    op.execute(
        "CREATE INDEX ix_product_models_service_types "
        "ON product_models USING GIN (service_types)"
    )


def downgrade() -> None:
    """Downgrade schema.

    Lossy, but only of a setting: which service types each model supported is
    gone, and re-upgrading puts everyone back on the Installation + Demo default.
    """
    op.execute("DROP INDEX IF EXISTS ix_product_models_service_types")
    op.drop_constraint(
        "ck_product_models_service_types", "product_models", type_="check"
    )
    op.drop_column("product_models", "service_types")
