"""vendors master and feature keys

Revision ID: c1e8b4a7d930
Revises: b7c41d9e2f08
Create Date: 2026-08-18

Vendors — the brands a company stocks, and who to call about them. A record,
not an account: nobody signs in as a vendor. Product models point at one to get
their brand, which lands in the next migration.

Company-scoped like the product master, and carrying the `(company_id, id)`
UNIQUE that `product_models`' composite FK will point at. Two companies may both
stock Samsung; they each get their own row, because the contact person, the
GSTIN they buy against and whether the relationship is live are all theirs.

Case-insensitive uniqueness on the name AND the GSTIN is hand-written here —
SQLAlchemy cannot express a functional index in a table constraint. Both are
PARTIAL on `deleted_at IS NULL`, so removing a vendor frees its name for reuse
rather than poisoning it.

The feature keys are seeded for `admin` and `national_head` ONLY. Absent rows
COALESCE to false, so a Regional Head, an Area Manager and a technician get
nothing, which is the requirement. Note that a company admin can still enable
the feature for a lower role through `company_role_features` — that is what the
`require_min_rank(NATIONAL_HEAD)` guard in the router is for, and why the rule
is not left to this seed alone.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes and mistakes them for stale.
Those drops are intentionally absent.

No vendor rows are seeded here. Vendors are tenant data, so they are seeded
per-company by `app/scripts/seed_catalogue.py`; migrations seed global reference
data only.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1e8b4a7d930'
down_revision: Union[str, Sequence[str], None] = 'b7c41d9e2f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (key, label, parent_key, sort_order) — 88/89 sit beside masters at 85/86.
FEATURES = [
    ("vendors.view", "Vendors", None, 88),
    ("vendors.edit", "Edit Vendors", "vendors.view", 89),
]
#: National Head and above. Superadmin is absent on purpose: they are a platform
#: role with no membership, and their feature set is only companies.*.
ROLES = ["admin", "national_head"]


def _audit_columns() -> list[sa.Column]:
    """IdMixin + AuditMixin + SoftDeleteMixin, spelled out once."""
    return [
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    ]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "vendors",
        *_audit_columns(),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("gst_number", sa.String(length=15), nullable=False),
        # Nullable: only an MCA-registered company has a CIN. A proprietorship
        # or partnership vendor is normal and has none.
        sa.Column("cin", sa.String(length=21), nullable=True),
        sa.Column("contact_person", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        # One free-text box, unlike companies, which splits line 1 / line 2.
        # City, state and pincode stay separate because they are the parts
        # anything downstream would ever filter or group on.
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("pincode", sa.String(length=10), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendors_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
        # What product_models' composite FK points at, so a model physically
        # cannot be branded with another company's vendor.
        sa.UniqueConstraint("company_id", "id", name="uq_vendors_company_id_id"),
    )
    op.create_index("ix_vendors_company_id", "vendors", ["company_id"])

    # Case-insensitive, scoped to the company, live rows only.
    op.execute(
        "CREATE UNIQUE INDEX uq_vendors_company_name_lower "
        "ON vendors (company_id, lower(name)) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_vendors_company_gst_lower "
        "ON vendors (company_id, lower(gst_number)) "
        "WHERE deleted_at IS NULL"
    )

    conn = op.get_bind()

    for key, label, parent_key, sort_order in FEATURES:
        conn.execute(
            sa.text(
                """
                INSERT INTO features (key, label, parent_key, sort_order)
                SELECT CAST(:key AS varchar), CAST(:label AS varchar),
                       CAST(:parent_key AS varchar), CAST(:sort_order AS integer)
                WHERE NOT EXISTS (
                    SELECT 1 FROM features f WHERE f.key = CAST(:key AS varchar)
                )
                """
            ),
            {
                "key": key,
                "label": label,
                "parent_key": parent_key,
                "sort_order": sort_order,
            },
        )

    # CAST(...) on both sides: a parameter reused in a SELECT list and a WHERE
    # makes Postgres raise AmbiguousParameter.
    for role in ROLES:
        for key, *_rest in FEATURES:
            conn.execute(
                sa.text(
                    """
                    INSERT INTO role_feature_defaults (role, feature_id, enabled)
                    SELECT CAST(:role AS varchar), f.id, true
                    FROM features f
                    WHERE f.key = CAST(:key AS varchar)
                      AND NOT EXISTS (
                          SELECT 1 FROM role_feature_defaults rfd
                          WHERE rfd.role = CAST(:role AS varchar)
                            AND rfd.feature_id = f.id
                      )
                    """
                ),
                {"role": role, "key": key},
            )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    for key, *_rest in FEATURES:
        for table in ("role_feature_defaults", "company_role_features"):
            conn.execute(
                sa.text(
                    f"""
                    DELETE FROM {table}
                    WHERE feature_id IN (
                        SELECT id FROM features WHERE key = CAST(:key AS varchar)
                    )
                    """
                ),
                {"key": key},
            )
        conn.execute(
            sa.text("DELETE FROM features WHERE key = CAST(:key AS varchar)"),
            {"key": key},
        )

    op.execute("DROP INDEX IF EXISTS uq_vendors_company_gst_lower")
    op.execute("DROP INDEX IF EXISTS uq_vendors_company_name_lower")
    op.drop_index("ix_vendors_company_id", table_name="vendors")
    op.drop_table("vendors")
