"""tickets

Revision ID: c5a91d3f7e28
Revises: b8e42a6d1f07
Create Date: 2026-08-18

The unit of work the whole system exists to move. Purely additive — no existing
table loses anything.

One thing it DOES add elsewhere: `product_models` gains its `(company_id, id)`
UNIQUE. Every other master already had one; models did not, because until now
nothing hung off a model and there was nothing for a composite FK to point at.
A ticket names one, so now there is.

Every link to a master is a COMPOSITE FK on `(company_id, …)`, and all four are
RESTRICT rather than CASCADE. A ticket is the record that somebody was promised
something; it must not be deleted out from under itself because a vendor was
tidied up. The services already refuse to delete a referenced row with a message
— this is the backstop underneath that.

`sla_due_at` is stored rather than computed on read because the list sorts and
filters on SLA urgency, and that has to happen in SQL. Deriving it per row in
Python would make a page's `total` disagree with the rows on it.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes and mistakes them for stale.
Those drops are intentionally absent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5a91d3f7e28'
down_revision: Union[str, Sequence[str], None] = 'b8e42a6d1f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _audit_columns() -> list[sa.Column]:
    """IdMixin + AuditMixin + SoftDeleteMixin, spelled out once."""
    return [
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    ]


def upgrade() -> None:
    """Upgrade schema."""
    # The target a ticket's composite FK to a model points at.
    op.create_unique_constraint(
        "uq_product_models_company_id_id", "product_models", ["company_id", "id"]
    )

    op.create_table(
        "tickets",
        *_audit_columns(),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("subcategory_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("service_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("serial_number", sa.String(length=64), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("pincode", sa.String(length=6), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=False),
        sa.Column("service_level_hours", sa.SmallInteger(), nullable=False),
        sa.Column("slot_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("slot_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("technician_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_tickets_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "vendor_id"],
            ["vendors.company_id", "vendors.id"],
            name="fk_tickets_company_vendor",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "subcategory_id"],
            ["product_subcategories.company_id", "product_subcategories.id"],
            name="fk_tickets_company_subcategory",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "model_id"],
            ["product_models.company_id", "product_models.id"],
            name="fk_tickets_company_model",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "technician_id"],
            ["technician_profiles.company_id", "technician_profiles.id"],
            name="fk_tickets_company_technician",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("company_id", "code", name="uq_tickets_company_code"),
    )

    op.create_index("ix_tickets_company_status", "tickets", ["company_id", "status"])
    # The routing probe every area manager runs on every page load.
    op.create_index("ix_tickets_company_pincode", "tickets", ["company_id", "pincode"])
    op.create_index(
        "ix_tickets_company_sla_due_at", "tickets", ["company_id", "sla_due_at"]
    )
    op.create_index("ix_tickets_technician_id", "tickets", ["technician_id"])

    op.create_check_constraint(
        "ck_tickets_service_level_hours",
        "tickets",
        "service_level_hours IN (12, 24, 36, 48)",
    )
    op.create_check_constraint(
        "ck_tickets_service_type",
        "tickets",
        "service_type IN ('Installation + Demo', 'Tech Visit', 'Service')",
    )
    op.create_check_constraint(
        "ck_tickets_status",
        "tickets",
        "status IN ('New', 'Slot Pending', 'Assigned', 'In Progress', "
        "'AI Review', 'Escalated', 'Closed', 'Force-Closed', 'Cancelled')",
    )
    # Half a slot is not a time.
    op.create_check_constraint(
        "ck_tickets_slot_both_or_neither",
        "tickets",
        "(slot_start IS NULL) = (slot_end IS NULL) "
        "AND (slot_end IS NULL OR slot_end > slot_start)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("tickets")
    op.drop_constraint(
        "uq_product_models_company_id_id", "product_models", type_="unique"
    )
