"""Order the ticket trail by an identity column, not by a timestamp.

`ticket_events` shipped one migration ago sorted by `created_at, id`, and the
deployed trail immediately showed:

    slot_confirmed   Slot confirmed & locked
    created          Ticket created            <- after the thing it preceded

Because Postgres `now()` is the TRANSACTION's start time rather than the
statement's, every event written in one transaction carries the identical
timestamp — and creating a ticket with a slot already writes two. The sort then
fell through to `id`, which is a random UUID and therefore no order at all. The
same applied to the backfill, which gave a ticket's `created` and
`slot_confirmed` rows the ticket's own `created_at`.

`seq` is `GENERATED BY DEFAULT AS IDENTITY`: monotonic per table, assigned at
INSERT, so the stored order is the order things happened and stays that way.

Existing rows are numbered by when they happened and then by what can only have
come first — a ticket is created before its slot is confirmed — rather than by
physical row order, which is not a guarantee Postgres makes.

The identity sequence is then set past the highest backfilled value, or the
first new event collides with row 1.
"""

import sqlalchemy as sa
from alembic import op

revision = "c93f5d81a06b"
down_revision = "7b1e4a9c05d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Nullable first: the values have to be computed before the column can be
    # NOT NULL, and an IDENTITY column cannot be added and back-dated in one go.
    op.add_column("ticket_events", sa.Column("seq", sa.BigInteger(), nullable=True))
    op.execute(
        """
        WITH ordered AS (
            SELECT id, row_number() OVER (
                ORDER BY created_at,
                         CASE kind
                             WHEN 'created' THEN 0
                             WHEN 'slot_requested' THEN 1
                             WHEN 'slot_confirmed' THEN 2
                             ELSE 3
                         END,
                         id
            ) AS n
            FROM ticket_events
        )
        UPDATE ticket_events e SET seq = ordered.n FROM ordered WHERE ordered.id = e.id
        """
    )
    op.alter_column("ticket_events", "seq", nullable=False)
    op.execute(
        "ALTER TABLE ticket_events ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    # Start the sequence after what the backfill used.
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('ticket_events', 'seq'),
            coalesce((SELECT max(seq) FROM ticket_events), 0) + 1,
            false
        )
        """
    )

    # The timeline reads one ticket's events in `seq` order; with `seq` in the
    # index the sort comes off the index instead of being done in memory.
    op.drop_index("ix_ticket_events_company_ticket", table_name="ticket_events")
    op.create_index(
        "ix_ticket_events_company_ticket",
        "ticket_events",
        ["company_id", "ticket_id", "seq"],
    )


def downgrade() -> None:
    op.drop_index("ix_ticket_events_company_ticket", table_name="ticket_events")
    op.create_index(
        "ix_ticket_events_company_ticket", "ticket_events", ["company_id", "ticket_id"]
    )
    op.execute("ALTER TABLE ticket_events ALTER COLUMN seq DROP IDENTITY IF EXISTS")
    op.drop_column("ticket_events", "seq")
