"""ticket slot confirmation

Revision ID: d6b83e2c4a91
Revises: c5a91d3f7e28
Create Date: 2026-08-18

The customer's half of intake. A ticket raised without a slot now carries a
token, sent to the customer over WhatsApp, that opens a page where they pick a
two-hour window. Confirming locks the slot and moves the ticket from Slot
Pending to New, which is the point technicians first hear it exists.

`slot_token` is stored in CLEAR, deliberately, and for the same reasons as
`technician_invites.token`: the console shows a copyable link when WhatsApp
refuses, and a resend has to send the same one — neither survives hashing. It
is single-use, it stops working once the SLA window passes, and what it guards
is a two-hour appointment rather than an account.

Its UNIQUE is global rather than per company, because the token IS the URL and
is resolved before any company is known. PARTIAL on NOT NULL, so the many
tickets ops slotted themselves — which need no token at all — do not all
collide on null.

Purely additive.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes and mistakes them for stale.
Those drops are intentionally absent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6b83e2c4a91'
down_revision: Union[str, Sequence[str], None] = 'c5a91d3f7e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("tickets", sa.Column("slot_token", sa.String(length=64), nullable=True))
    op.add_column(
        "tickets",
        sa.Column("slot_confirmed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tickets",
        sa.Column(
            "slot_request_status",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'not_needed'"),
        ),
    )
    op.add_column(
        "tickets",
        sa.Column("slot_request_error", sa.String(length=255), nullable=True),
    )

    # Partial: only tickets that actually asked the customer hold a token.
    op.execute(
        "CREATE UNIQUE INDEX uq_tickets_slot_token "
        "ON tickets (slot_token) WHERE slot_token IS NOT NULL"
    )
    op.create_check_constraint(
        "ck_tickets_slot_request_status",
        "tickets",
        "slot_request_status IN ('not_needed', 'pending', 'sent', 'failed')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_tickets_slot_request_status", "tickets", type_="check")
    op.execute("DROP INDEX IF EXISTS uq_tickets_slot_token")
    op.drop_column("tickets", "slot_request_error")
    op.drop_column("tickets", "slot_request_status")
    op.drop_column("tickets", "slot_confirmed_at")
    op.drop_column("tickets", "slot_token")
