"""notifications can also address a vendor

Revision ID: d91c8f17eaf4
Revises: 25e087e3ce6e
Create Date: 2026-08-26 16:05:26.061488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd91c8f17eaf4'
down_revision: Union[str, Sequence[str], None] = '25e087e3ce6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('vendor_id', sa.Uuid(), nullable=True))
    op.create_index('ix_notifications_company_vendor', 'notifications', ['company_id', 'vendor_id'], unique=False)
    op.create_foreign_key('fk_notifications_company_vendor', 'notifications', 'vendors', ['company_id', 'vendor_id'], ['company_id', 'id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_company_vendor', 'notifications', type_='foreignkey')
    op.drop_index('ix_notifications_company_vendor', table_name='notifications')
    op.drop_column('notifications', 'vendor_id')
    # ### end Alembic commands ###
