"""partner invites over whatsapp

Revision ID: dafb231566bb
Revises: fb71d2baf158
Create Date: 2026-08-09

Adds the partner-invite table plus two features — partners.view and
partners.invite — default-on for admin, national head, regional head and area
manager. The Partners screens were previously ungated in the console.

NB: the autogenerated diff wanted to DROP uq_companies_gst_lower,
uq_companies_slug_lower and uq_users_email_lower — Alembic does not recognise
hand-written LOWER() functional indexes and mistakes them for stale. Those drops
are intentionally removed here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dafb231566bb'
down_revision: Union[str, Sequence[str], None] = 'fb71d2baf158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FEATURES = [
    ("partners.view", "Partners", 55),
    ("partners.invite", "Invite Partners", 56),
]
ROLES = ["admin", "national_head", "regional_head", "area_manager"]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('partner_invites',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('partner_type', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('invited_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('wa_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_partner_invites_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_membership_id'], ['memberships.id'], name=op.f('fk_partner_invites_invited_by_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_partner_invites_region_id_regions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], name=op.f('fk_partner_invites_registered_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_invites')),
    sa.UniqueConstraint('token', name=op.f('uq_partner_invites_token'))
    )
    op.create_index('ix_partner_invites_company_status', 'partner_invites', ['company_id', 'status'], unique=False)
    op.create_index('ix_partner_invites_region_id', 'partner_invites', ['region_id'], unique=False)

    # One LIVE invite per number per company. Partial, so a cancelled number can
    # be invited again — and so a registered partner doesn't block a re-invite
    # after they are removed.
    op.execute(
        "CREATE UNIQUE INDEX uq_partner_invites_company_phone_live "
        "ON partner_invites (company_id, phone) "
        "WHERE status <> 'cancelled'"
    )

    # ─── features ─────────────────────────────────────────────────────────
    conn = op.get_bind()
    for key, label, sort_order in FEATURES:
        conn.execute(
            sa.text(
                "INSERT INTO features (key, label, sort_order) "
                "VALUES (:key, :label, :sort_order)"
            ),
            {"key": key, "label": label, "sort_order": sort_order},
        )
        for role in ROLES:
            # Cast both sides: a parameter reused in a SELECT list and a WHERE
            # makes Postgres report AmbiguousParameter.
            conn.execute(
                sa.text(
                    """
                    INSERT INTO role_feature_defaults (role, feature_id, enabled)
                    SELECT CAST(:role AS varchar), f.id, true
                    FROM features f
                    WHERE f.key = CAST(:key AS varchar)
                    """
                ),
                {"role": role, "key": key},
            )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    for key, _label, _sort in FEATURES:
        for table in ("role_feature_defaults", "company_role_features"):
            conn.execute(
                sa.text(
                    f"DELETE FROM {table} WHERE feature_id IN "
                    "(SELECT id FROM features WHERE key = CAST(:key AS varchar))"
                ),
                {"key": key},
            )
        conn.execute(
            sa.text("DELETE FROM features WHERE key = CAST(:key AS varchar)"),
            {"key": key},
        )

    op.execute("DROP INDEX IF EXISTS uq_partner_invites_company_phone_live")
    op.drop_index('ix_partner_invites_region_id', table_name='partner_invites')
    op.drop_index('ix_partner_invites_company_status', table_name='partner_invites')
    op.drop_table('partner_invites')
