"""technician otp signin nullable email password

Revision ID: e3cb6cf2941c
Revises: a9c9817495b0
Create Date: 2026-08-10

A technician signs in with a phone and a one-time code. There is no password in
this product and most technicians have no work email, so `users.email` and
`users.password_hash` both become nullable and the phone becomes the identity.

`uq_users_email_lower` is deliberately NOT touched. It is a plain UNIQUE index,
and Postgres treats NULLs as distinct in one — so any number of technicians may
carry `email IS NULL`. Making it NULLS NOT DISTINCT would break exactly the case
this migration exists to allow.

The new phone index is partial twice over:
  role = 'technician'   so the existing free-typed manager phones ("+91 98220
                        66301" vs "9822066301") need no backfill and cannot
                        collide with it
  deleted_at IS NULL    so a removed technician's number is re-usable — which
                        means the OTP lookup must filter deleted_at itself, and
                        the create paths must revive a soft-deleted technician
                        rather than inserting a second one

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes. Those drops are absent on
purpose.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3cb6cf2941c'
down_revision: Union[str, Sequence[str], None] = 'a9c9817495b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "users", "email", existing_type=sa.String(length=255), nullable=True
    )
    op.alter_column(
        "users", "password_hash", existing_type=sa.Text(), nullable=True
    )

    op.execute(
        "CREATE UNIQUE INDEX uq_users_phone_technician ON users (phone) "
        "WHERE role = 'technician' AND phone IS NOT NULL AND deleted_at IS NULL"
    )

    op.create_table(
        "otp_codes",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("invite_id", sa.Uuid(), nullable=True),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_channel", sa.String(length=16), nullable=True),
        sa.Column("wa_message_id", sa.String(length=128), nullable=True),
        sa.Column("wa_error", sa.Text(), nullable=True),
        sa.Column("request_ip", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_otp_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["technician_invites.id"],
            name=op.f("fk_otp_codes_invite_id_technician_invites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_codes")),
        sa.CheckConstraint(
            "purpose IN ('login','invite')", name="ck_otp_codes_purpose"
        ),
    )
    op.create_index("ix_otp_codes_phone_created", "otp_codes", ["phone", "created_at"])
    op.create_index("ix_otp_codes_purpose_phone", "otp_codes", ["purpose", "phone"])
    op.create_index("ix_otp_codes_ip_created", "otp_codes", ["request_ip", "created_at"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_otp_codes_ip_created", table_name="otp_codes")
    op.drop_index("ix_otp_codes_purpose_phone", table_name="otp_codes")
    op.drop_index("ix_otp_codes_phone_created", table_name="otp_codes")
    op.drop_table("otp_codes")
    op.execute("DROP INDEX IF EXISTS uq_users_phone_technician")

    # Lossy, and loudly so: NOT NULL cannot be restored over existing NULLs.
    # Technician rows get a placeholder identity rather than being deleted —
    # they lose the ability to sign in by password, which they never had.
    op.execute(
        "UPDATE users SET email = 'technician+' || id::text || '@invalid.local' "
        "WHERE email IS NULL"
    )
    op.execute("UPDATE users SET password_hash = '!' WHERE password_hash IS NULL")
    op.alter_column(
        "users", "password_hash", existing_type=sa.Text(), nullable=False
    )
    op.alter_column(
        "users", "email", existing_type=sa.String(length=255), nullable=False
    )
