"""enforce tenancy on product and technician links

Revision ID: ed5d2a079020
Revises: d2a6e47420a1
Create Date: 2026-08-11

Makes "everything belongs to one company" a DATABASE guarantee rather than a
service-layer habit.

Every write path already checks it, and the tests prove company A cannot read,
edit or extend company B's catalogue. But the checks are application-level, and
`membership_pincodes` already carries the counter-argument in its own docstring:
"an application-level check alone would race under concurrent writes". The same
reasoning applies to every parent/child link here.

The technique is the one `memberships` already uses for `manager_id`: give the
parent a UNIQUE on (company_id, id) so a child can carry a COMPOSITE foreign key
on (company_id, parent_id). A row whose parent lives in another company then
cannot be written at all — there is no combination of concurrent requests, bad
input or future refactor that produces one.

Five links are converted, each replacing its single-column FK so the two cannot
disagree about ON DELETE:

    product_subcategories   -> product_categories
    product_models          -> product_subcategories
    technician_subcategories-> technician_profiles
    technician_subcategories-> product_subcategories   <- the one with no company_id at all
    technician_pincodes     -> technician_profiles

`technician_subcategories` also gains `company_id`, backfilled from the
technician's own profile. It was the only join table in the schema with no tenant
column, which meant "this technician is certified for a subcategory from their
own company's catalogue" had no representation in the database whatsoever.

NB: the autogenerated diff wants to DROP `uq_companies_gst_lower`,
`uq_companies_slug_lower` and `uq_users_email_lower` — Alembic does not
recognise hand-written LOWER() functional indexes. Those drops are absent on
purpose.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed5d2a079020'
down_revision: Union[str, Sequence[str], None] = 'd2a6e47420a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ── the tenant column that was missing entirely ────────────────────────
    op.add_column(
        "technician_subcategories", sa.Column("company_id", sa.Uuid(), nullable=True)
    )
    op.execute(
        """
        UPDATE technician_subcategories ts
        SET company_id = tp.company_id
        FROM technician_profiles tp
        WHERE tp.id = ts.technician_id
        """
    )
    # Anything the backfill could not resolve is an orphan that should never
    # have existed; there is no correct company to give it.
    op.execute("DELETE FROM technician_subcategories WHERE company_id IS NULL")
    op.alter_column(
        "technician_subcategories", "company_id", existing_type=sa.Uuid(), nullable=False
    )
    op.create_foreign_key(
        op.f("fk_technician_subcategories_company_id_companies"),
        "technician_subcategories",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # ── parents get the UNIQUE a composite FK can point at ─────────────────
    for table in (
        "product_categories",
        "product_subcategories",
        "technician_profiles",
    ):
        op.create_unique_constraint(
            f"uq_{table}_company_id_id", table, ["company_id", "id"]
        )

    # ── children swap their single-column FK for a composite one ───────────
    # (child, column, parent, ondelete)
    links = [
        ("product_subcategories", "category_id", "product_categories", "CASCADE"),
        ("product_models", "subcategory_id", "product_subcategories", "CASCADE"),
        (
            "technician_subcategories",
            "technician_id",
            "technician_profiles",
            "CASCADE",
        ),
        # RESTRICT: removing a subcategory somebody is certified for must be
        # refused with a message, not silently decertify them.
        (
            "technician_subcategories",
            "subcategory_id",
            "product_subcategories",
            "RESTRICT",
        ),
        ("technician_pincodes", "technician_id", "technician_profiles", "CASCADE"),
    ]

    conn = op.get_bind()
    for child, column, parent, ondelete in links:
        # Look the old name up rather than spelling it out: Postgres caps
        # identifiers at 63 characters and SQLAlchemy silently rewrites longer
        # ones with a hash suffix, so at least one of these is not the name the
        # model appears to give it.
        old_fk = conn.execute(
            sa.text(
                """
                SELECT conname FROM pg_constraint
                WHERE contype = 'f'
                  AND conrelid = CAST(:child AS regclass)
                  AND confrelid = CAST(:parent AS regclass)
                  AND conkey = ARRAY[(
                      SELECT attnum FROM pg_attribute
                      WHERE attrelid = CAST(:child AS regclass)
                        AND attname = CAST(:column AS name)
                  )]
                """
            ),
            {"child": child, "parent": parent, "column": column},
        ).scalar()
        if old_fk:
            op.drop_constraint(old_fk, child, type_="foreignkey")
        op.create_foreign_key(
            f"fk_{child}_company_{column.removesuffix('_id')}",
            child,
            parent,
            ["company_id", column],
            ["company_id", "id"],
            ondelete=ondelete,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Restored with names that fit the 63-character cap, rather than the
    # originals — one of those was over it and had been rewritten with a hash.
    restore = [
        ("technician_pincodes", "technician_id", "technician_profiles", "CASCADE"),
        (
            "technician_subcategories",
            "subcategory_id",
            "product_subcategories",
            "RESTRICT",
        ),
        (
            "technician_subcategories",
            "technician_id",
            "technician_profiles",
            "CASCADE",
        ),
        ("product_models", "subcategory_id", "product_subcategories", "CASCADE"),
        (
            "product_subcategories",
            "category_id",
            "product_categories",
            "CASCADE",
        ),
    ]
    for child, col, parent, ondelete in restore:
        op.drop_constraint(
            f"fk_{child}_company_{col.removesuffix('_id')}", child, type_="foreignkey"
        )
        op.create_foreign_key(
            f"fk_{child}_{col.removesuffix('_id')}",
            child,
            parent,
            [col],
            ["id"],
            ondelete=ondelete,
        )

    for table in (
        "technician_profiles",
        "product_subcategories",
        "product_categories",
    ):
        op.drop_constraint(f"uq_{table}_company_id_id", table, type_="unique")

    op.drop_constraint(
        op.f("fk_technician_subcategories_company_id_companies"),
        "technician_subcategories",
        type_="foreignkey",
    )
    op.drop_column("technician_subcategories", "company_id")
