import { useState } from "react";
import {
  DataTable,
  type Column,
  type TypedFilterDef,
} from "@/components/shared/DataTable";
import { EditAccessDialog } from "@/components/settings/EditAccessDialog";
import { ROLE_OPTIONS } from "@/components/settings/userSchema";
import { UserAvatar } from "@/components/shared/UserAvatar";
import { Button } from "@/components/ui/button";
import {
  filterValue,
  useParamsWriter,
  withFilter,
  withSearch,
} from "@/hooks/useListParams";
import { cn } from "@/lib/utils";
import type { ListParams, PaginationMeta } from "@/types/api";
import type { Role, User } from "@/types";

/**
 * Console users and the scope each one works inside.
 *
 * This table is a *record* of who has access, not the mechanism that grants it:
 * RBAC is enforced server-side. Hiding or showing a row here would change
 * nothing about what a request is allowed to do.
 */

/**
 * The management hierarchy, widest scope first: NH covers every region, an RSH
 * one region, an ASM a pincode range, and Ops Staff do intake only. The tints
 * are the prototype's, mapped onto existing semantic tokens.
 *
 * Static strings, one per role — an interpolated `bg-status-${role}-bg` is
 * never generated by Tailwind and renders transparent.
 */
const ROLE_CLASS: Record<Role, string> = {
  Admin: "bg-brand-100 text-brand-400",
  NH: "bg-status-new-bg text-status-new",
  RSH: "bg-status-assigned-bg text-status-assigned",
  ASM: "bg-ok-bg text-ok",
  "Ops Staff": "bg-surface-3 text-ink-2",
};

/** Colour is the second signal here; the status word is always rendered. */
const STATUS_CLASS: Record<User["status"], string> = {
  Active: "text-ok",
  Invited: "text-warn",
  Suspended: "text-danger",
};

const STATUSES: User["status"][] = ["Active", "Invited", "Suspended"];

interface UserTableProps {
  /** Exactly the rows the server returned for `params` — one page of them. */
  users?: User[];
  /** The envelope's pagination block. Absent on the first load. */
  meta?: PaginationMeta;
  params: ListParams;
  onParams: (next: ListParams) => void;
  isLoading: boolean;
  error: unknown;
  onRetry: () => void;
  toolbarActions?: React.ReactNode;
}

export function UserTable({
  users,
  meta,
  params,
  onParams,
  isLoading,
  error,
  onRetry,
  toolbarActions,
}: UserTableProps) {
  // The row being edited. One dialog for the whole table, not one per row.
  const [editing, setEditing] = useState<User | null>(null);

  // Search and both filters are query parameters now, so each control writes
  // through here instead of narrowing rows in the browser.
  const write = useParamsWriter(params, onParams);

  /*
   * No `sortValue` anywhere below, on purpose.
   *
   * Sorting is the server's job now — `ListParams` carries `sortBy` /
   * `sortDir` and `services/settings.ts` applies them, including the
   * minutes-since-last-seen comparison "Last active" needs. But `DataTable`'s
   * server mode wires only page and page size to `server.onParams`; its header
   * buttons still toggle local sort state, which a passthrough table ignores.
   * Declaring `sortValue` here would render arrows that reorder nothing and
   * announce an `aria-sort` that is not true. Restore them the moment
   * `shared/DataTable` reports sort through `onParams`.
   */
  const columns: Column<User>[] = [
    {
      id: "name",
      header: "User",
      sortValue: (u) => u.name,
      cell: (u) => (
        <div className="flex items-center gap-2.5">
          <UserAvatar
            name={u.name}
            src={u.photoUrl}
            className="size-8.5 text-xs"
          />
          <div>
            <div className="font-medium">{u.name}</div>
            <div className="text-[11px] text-ink-3">{u.email}</div>
          </div>
        </div>
      ),
    },
    {
      id: "role",
      header: "Role",
      sortValue: (u) => u.role,
      cell: (u) => (
        // The role word carries the meaning; the tint only reinforces it.
        <span
          className={cn(
            "inline-flex items-center rounded-full px-2.25 py-0.75 text-[11px] font-semibold whitespace-nowrap",
            ROLE_CLASS[u.role]
          )}
        >
          {u.role}
        </span>
      ),
    },
    { id: "region", header: "Scope", cell: (u) => u.region },
    {
      id: "last",
      header: "Last active",
      sortValue: (u) => u.last,
      cell: (u) => <span className="text-xs text-ink-2">{u.last}</span>,
    },
    {
      id: "status",
      header: "Status",
      sortValue: (u) => u.status,
      cell: (u) => (
        <span
          className={cn(
            "inline-flex items-center gap-1.5 text-xs font-semibold whitespace-nowrap",
            STATUS_CLASS[u.status]
          )}
        >
          <span
            className="size-1.75 shrink-0 rounded-full bg-current"
            aria-hidden
          />
          {u.status}
        </span>
      ),
    },
    {
      id: "edit",
      // The actions column has no visible heading in the approved design, but
      // an empty `<th>` is a hole for screen readers.
      header: "Edit access",
      hideHeader: true,
      align: "right",
      cell: (u) => (
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setEditing(u)}
          aria-label={`Edit access for ${u.name}`}
          className="-mr-2 text-brand-400"
        >
          Edit access
        </Button>
      ),
    },
  ];

  /*
   * Controlled against the query string. `match` is part of the filter
   * contract but is never called in server mode — the rows arrive already
   * narrowed — so it is kept as an accurate statement of what each filter
   * means rather than a second implementation of it.
   */
  const filters: TypedFilterDef<User>[] = [
    {
      id: "role",
      label: "Role",
      variant: "select",
      // Hierarchy order, widest first — the same source the invite form uses.
      options: ROLE_OPTIONS.map((r) => ({ value: r.value, label: r.value })),
      value: filterValue(params, "role"),
      onChange: (v) => write((p) => withFilter(p, "role", v)),
      match: (u, value) => u.role === value,
    },
    {
      id: "status",
      label: "Status",
      variant: "select",
      options: STATUSES.map((s) => ({ value: s, label: s })),
      value: filterValue(params, "status"),
      onChange: (v) => write((p) => withFilter(p, "status", v)),
      match: (u, value) => u.status === value,
    },
  ];

  return (
    <>
      <DataTable
        errorTitle="Couldn't load users"
        caption="Users & roles"
        data={users}
        columns={columns}
        getRowId={(u) => u.id}
        isLoading={isLoading}
        error={error}
        onRetry={onRetry}
        search={{
          placeholder: "Search users by name or email…",
          value: params.search ?? "",
          onChange: (v) => write((p) => withSearch(p, v)),
        }}
        filters={filters}
        server={{ meta, params, onParams }}
        toolbarActions={toolbarActions}
        minWidth="51.25rem"
        emptyTitle="No users yet"
        emptyDescription="Invited and active console users appear here with their role and scope."
        filteredEmptyTitle="No users match those filters"
        filteredEmptyDescription="Try a different role or status, or clear the search."
      />

      <EditAccessDialog
        user={editing}
        onOpenChange={(open) => {
          if (!open) setEditing(null);
        }}
      />
    </>
  );
}
