import {
  HeadTr,
  Table,
  TableBody,
  TableHeader,
  Td,
  Th,
  Tr,
} from "@/components/shared/DataTable";
import { EmptyState, ErrorState, TableSkeleton } from "@/components/shared/states";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { Role, User } from "@/types";

/**
 * Console users and the scope each one works inside.
 *
 * This table is a *record* of who has access, not the mechanism that grants it:
 * RBAC is enforced server-side. Hiding or showing a row here would change
 * nothing about what a request is allowed to do.
 */

const COLUMNS = ["User", "Role", "Scope", "Last active", "Status"];

/**
 * The management hierarchy, widest scope first: NH covers every region, an RSH
 * one region, an ASM a pincode range, and Ops Staff do intake only. The tints
 * are the prototype's, mapped onto existing semantic tokens.
 *
 * Static strings, one per role — an interpolated `bg-status-${role}-bg` is
 * never generated by Tailwind and renders transparent.
 */
const ROLE_CLASS: Record<Role, string> = {
  NH: "bg-status-new-bg text-status-new",
  RSH: "bg-status-assigned-bg text-status-assigned",
  ASM: "bg-ok-bg text-ok",
  "Ops Staff": "bg-surface-3 text-ink-2",
};

/** Colour is the second signal here; the status word is always rendered. */
const STATUS_CLASS: Record<User["status"], string> = {
  Active: "text-ok",
  Invited: "text-warn",
  Suspended: "text-danger",
};

interface UserTableProps {
  users?: User[];
  isLoading: boolean;
  error: unknown;
  onRetry: () => void;
}

export function UserTable({ users, isLoading, error, onRetry }: UserTableProps) {
  if (error) {
    return <ErrorState title="Couldn't load users" error={error} onRetry={onRetry} />;
  }

  if (!isLoading && !users?.length) {
    return (
      <EmptyState
        title="No users yet"
        description="Invited and active console users appear here with their role and scope."
      />
    );
  }

  return (
    <div className="scroll-x">
      <Table className="min-w-205">
        <caption className="sr-only">Users &amp; roles</caption>
        <TableHeader>
          <HeadTr>
            {COLUMNS.map((c) => (
              <Th key={c} scope="col">
                {c}
              </Th>
            ))}
            <Th scope="col">
              {/* The actions column has no visible heading in the approved
                  design, but an empty `<th>` is a hole for screen readers. */}
              <span className="sr-only">Edit access</span>
            </Th>
          </HeadTr>
        </TableHeader>
        <TableBody>
          {isLoading ? (
            <TableSkeleton rows={7} cols={COLUMNS.length + 1} />
          ) : (
            users?.map((u) => (
              <Tr key={u.id}>
                <Td>
                  <div className="flex items-center gap-2.5">
                    <UserAvatar name={u.name} />
                    <div>
                      <div className="font-medium">{u.name}</div>
                      <div className="text-ink-3 text-[11px]">{u.email}</div>
                    </div>
                  </div>
                </Td>
                <Td>
                  <span
                    className={cn(
                      "inline-flex items-center rounded-full px-2.25 py-0.75 text-[11px] font-semibold whitespace-nowrap",
                      ROLE_CLASS[u.role],
                    )}
                  >
                    {u.role}
                  </span>
                </Td>
                <Td>{u.region}</Td>
                <Td>
                  <span className="text-ink-2 text-xs">{u.last}</span>
                </Td>
                <Td>
                  <span
                    className={cn(
                      "inline-flex items-center gap-1.5 text-xs font-semibold whitespace-nowrap",
                      STATUS_CLASS[u.status],
                    )}
                  >
                    <span
                      className="size-1.75 shrink-0 rounded-full bg-current"
                      aria-hidden
                    />
                    {u.status}
                  </span>
                </Td>
                <Td className="text-right">
                  {/* No access-editing form is designed yet, and permissions
                      are a server-side concern — so the action is present and
                      deliberately inert rather than invented. */}
                  <Button
                    variant="ghost"
                    size="sm"
                    disabled
                    aria-label={`Edit access for ${u.name}`}
                    className="text-brand-400 -mr-2"
                  >
                    Edit access
                  </Button>
                </Td>
              </Tr>
            ))
          )}
        </TableBody>
      </Table>
    </div>
  );
}

/** Initials disc. Decorative — the name is always rendered beside it. */
function UserAvatar({ name }: { name: string }) {
  const initials = name
    .split(" ")
    .map((part) => part[0] ?? "")
    .join("")
    .slice(0, 2);

  return (
    <span
      aria-hidden
      className="bg-status-assigned-bg text-brand-400 grid size-8.5 shrink-0 place-items-center rounded-full text-xs font-semibold"
    >
      {initials}
    </span>
  );
}
