import {
  HeadTr,
  Table,
  TableBody,
  TableHeader,
  Td,
  Th,
  Tr,
} from "@/components/shared/DataTable";
import { EmptyState, ErrorState, TableSkeleton } from "@/components/shared/states";
import { Button } from "@/components/ui/button";
import type { Vendor } from "@/types";

const COLUMNS = [
  "Vendor",
  "Intake channel",
  "API credentials",
  "Tickets (lifetime)",
  "Since",
  "Status",
];

/**
 * Requirement §4 — there are exactly three intake channels, and only one of
 * them is an integration. Most vendors have no CRM, so Excel and Manual are
 * primary paths rather than fallbacks; the channel therefore gets its own
 * column instead of being implied by whether a key exists.
 *
 * Static strings on purpose — an interpolated `bg-${channel}` is never
 * generated by Tailwind.
 */
const CHANNEL_CLASS: Record<Vendor["channel"], string> = {
  API: "bg-brand-100 text-brand-400",
  Excel: "bg-ok-bg text-ok",
  Manual: "bg-warn-bg text-warn",
};

const STATUS_CLASS: Record<Vendor["status"], string> = {
  Active: "text-ok",
  Paused: "text-warn",
};

/** The prototype's 32px squared monogram. */
function VendorMonogram({ name }: { name: string }) {
  return (
    <div
      aria-hidden
      className="bg-surface-3 text-ink-2 grid size-8 shrink-0 place-items-center rounded-md text-xs font-semibold"
    >
      {name.slice(0, 2).toUpperCase()}
    </div>
  );
}

interface VendorTableProps {
  vendors?: Vendor[];
  isLoading: boolean;
  error: unknown;
  onRetry: () => void;
}

export function VendorTable({ vendors, isLoading, error, onRetry }: VendorTableProps) {
  if (error) {
    return <ErrorState title="Couldn't load vendors" error={error} onRetry={onRetry} />;
  }

  if (!isLoading && !vendors?.length) {
    return (
      <EmptyState
        title="No vendors yet"
        description="Vendors appear here with their intake channel and lifetime ticket volume."
      />
    );
  }

  return (
    <div className="scroll-x">
      <Table className="min-w-205">
        <TableHeader>
          <HeadTr>
            {COLUMNS.map((c) => (
              <Th key={c} scope="col">
                {c}
              </Th>
            ))}
            <Th>
              <span className="sr-only">Manage</span>
            </Th>
          </HeadTr>
        </TableHeader>
        <TableBody>
          {isLoading ? (
            <TableSkeleton rows={5} cols={COLUMNS.length + 1} />
          ) : (
            vendors?.map((v) => {
              // Only API-channel vendors hold credentials; the rest carry the
              // em dash the prototype shows, which reads as nothing on its own.
              const hasKey = v.channel === "API" && v.key !== "—";

              return (
                <Tr key={v.id}>
                  <Td>
                    <div className="flex items-center gap-2.5">
                      <VendorMonogram name={v.name} />
                      <span className="font-medium">{v.name}</span>
                    </div>
                  </Td>

                  <Td>
                    {/* Never colour alone — the channel word is always present. */}
                    <span
                      className={`inline-block rounded-full px-2.25 py-0.75 text-[11px] font-semibold ${CHANNEL_CLASS[v.channel]}`}
                    >
                      {v.channel}
                    </span>
                  </Td>

                  <Td>
                    {hasKey ? (
                      // Already masked at the source, and it stays that way —
                      // a full key must never reach the DOM.
                      <span className="text-ink-2 font-mono text-xs">{v.key}</span>
                    ) : (
                      <span className="text-ink-2 font-mono text-xs">
                        <span aria-hidden>—</span>
                        <span className="sr-only">Not applicable</span>
                      </span>
                    )}
                  </Td>

                  <Td className="tabular-nums">{v.tickets}</Td>
                  <Td className="tabular-nums">{v.since}</Td>

                  <Td>
                    <span
                      className={`inline-flex items-center gap-1.25 text-xs font-semibold ${STATUS_CLASS[v.status]}`}
                    >
                      <span
                        aria-hidden
                        className="size-1.75 rounded-full bg-current"
                      />
                      {v.status}
                    </span>
                  </Td>

                  <Td>
                    {/* No vendor form is designed yet, so the action is present
                        and deliberately inert rather than invented. */}
                    <Button
                      variant="link"
                      size="sm"
                      disabled
                      className="text-brand-400 h-auto p-0 text-xs font-semibold"
                    >
                      Manage
                      <span className="sr-only"> {v.name}</span>
                    </Button>
                  </Td>
                </Tr>
              );
            })
          )}
        </TableBody>
      </Table>
    </div>
  );
}
