import { useState } from "react";
import { VendorFormDialog } from "@/components/masters/VendorFormDialog";
import {
  INTAKE_CHANNELS,
  VENDOR_STATUSES,
} from "@/components/masters/vendorSchema";
import {
  DataTable,
  type Column,
  type TypedFilterDef,
} from "@/components/shared/DataTable";
import { Button } from "@/components/ui/button";
import {
  filterValue,
  useParamsWriter,
  withFilter,
  withSearch,
} from "@/hooks/useListParams";
import { cn } from "@/lib/utils";
import type { ListParams, PaginationMeta } from "@/types/api";
import type { Vendor } from "@/types";

/**
 * Requirement §4 — there are exactly three intake channels, and only one of
 * them is an integration. Most vendors have no CRM, so Excel and Manual are
 * primary paths rather than fallbacks; the channel therefore gets its own
 * column instead of being implied by whether a key exists.
 *
 * Static strings on purpose — an interpolated `bg-${channel}` is never
 * generated by Tailwind.
 */
const CHANNEL_CLASS: Record<Vendor["channel"], string> = {
  API: "bg-brand-100 text-brand-400",
  Excel: "bg-ok-bg text-ok",
  Manual: "bg-warn-bg text-warn",
};

const STATUS_CLASS: Record<Vendor["status"], string> = {
  Active: "text-ok",
  Paused: "text-warn",
};

/** The prototype's 32px squared monogram. */
function VendorMonogram({ name }: { name: string }) {
  return (
    <div
      aria-hidden
      className="grid size-8 shrink-0 place-items-center rounded-md bg-surface-3 text-xs font-semibold text-ink-2"
    >
      {name.slice(0, 2).toUpperCase()}
    </div>
  );
}

interface VendorTableProps {
  /** Exactly the rows the server returned for `params` — one page of them. */
  vendors?: Vendor[];
  /** The envelope's pagination block. Absent on the first load. */
  meta?: PaginationMeta;
  params: ListParams;
  onParams: (next: ListParams) => void;
  isLoading: boolean;
  error: unknown;
  onRetry: () => void;
  toolbarActions?: React.ReactNode;
}

export function VendorTable({
  vendors,
  meta,
  params,
  onParams,
  isLoading,
  error,
  onRetry,
  toolbarActions,
}: VendorTableProps) {
  // The managed vendor outlives the close so the dialog can animate out.
  const [managed, setManaged] = useState<Vendor | null>(null);
  const [open, setOpen] = useState(false);

  // Search and both filters are query parameters now, so each control writes
  // through here instead of narrowing rows in the browser.
  const write = useParamsWriter(params, onParams);

  /*
   * No `sortValue` anywhere below, on purpose.
   *
   * Sorting is the server's job now — `ListParams` carries `sortBy` /
   * `sortDir` and `services/masters.ts` applies them. But `DataTable`'s server
   * mode wires only page and page size to `server.onParams`; its header
   * buttons still toggle local sort state, which a passthrough table ignores.
   * Declaring `sortValue` here would render arrows that reorder nothing and
   * announce an `aria-sort` that is not true. Restore them the moment
   * `shared/DataTable` reports sort through `onParams`.
   */
  const columns: Column<Vendor>[] = [
    {
      id: "name",
      header: "Vendor",
      sortValue: (v) => v.name,
      cell: (v) => (
        <div className="flex items-center gap-2.5">
          <VendorMonogram name={v.name} />
          <span className="font-medium">{v.name}</span>
        </div>
      ),
    },
    {
      id: "channel",
      header: "Intake channel",
      sortValue: (v) => v.channel,
      cell: (v) => (
        // Never colour alone — the channel word is always present.
        <span
          className={cn(
            "inline-block rounded-full px-2.25 py-0.75 text-[11px] font-semibold",
            CHANNEL_CLASS[v.channel]
          )}
        >
          {v.channel}
        </span>
      ),
    },
    {
      id: "key",
      header: "API credentials",
      cell: (v) =>
        // Only API-channel vendors hold credentials; the rest carry the em
        // dash the prototype shows, which reads as nothing on its own. Already
        // masked at the source, and it stays that way — a full key must never
        // reach the DOM.
        v.channel === "API" && v.key !== "—" ? (
          <span className="font-mono text-xs text-ink-2">{v.key}</span>
        ) : (
          <span className="font-mono text-xs text-ink-2">
            <span aria-hidden>—</span>
            <span className="sr-only">Not applicable</span>
          </span>
        ),
    },
    {
      id: "tickets",
      header: "Tickets (lifetime)",
      sortValue: (v) => v.tickets,
      cellClassName: "tabular-nums",
      cell: (v) => v.tickets,
    },
    {
      id: "since",
      header: "Since",
      sortValue: (v) => Number(v.since),
      cellClassName: "tabular-nums",
      cell: (v) => v.since,
    },
    {
      id: "status",
      header: "Status",
      sortValue: (v) => v.status,
      cell: (v) => (
        <span
          className={cn(
            "inline-flex items-center gap-1.25 text-xs font-semibold",
            STATUS_CLASS[v.status]
          )}
        >
          <span aria-hidden className="size-1.75 rounded-full bg-current" />
          {v.status}
        </span>
      ),
    },
    {
      id: "manage",
      header: "Manage",
      hideHeader: true,
      cell: (v) => (
        // A Button, not a link: it opens a dialog rather than navigating.
        <Button
          type="button"
          variant="link"
          size="sm"
          className="h-auto p-0 text-xs font-semibold text-brand-400"
          onClick={() => {
            setManaged(v);
            setOpen(true);
          }}
        >
          Manage
          <span className="sr-only"> {v.name}</span>
        </Button>
      ),
    },
  ];

  /*
   * Controlled against the query string. `match` is part of the filter
   * contract but is never called in server mode — the rows arrive already
   * narrowed — so it is kept as an accurate statement of what each filter
   * means rather than a second implementation of it.
   */
  const filters: TypedFilterDef<Vendor>[] = [
    {
      id: "channel",
      label: "Intake channel",
      variant: "select",
      options: INTAKE_CHANNELS.map((c) => ({ value: c, label: c })),
      value: filterValue(params, "channel"),
      onChange: (v) => write((p) => withFilter(p, "channel", v)),
      match: (v, value) => v.channel === value,
    },
    {
      id: "status",
      label: "Status",
      variant: "select",
      options: VENDOR_STATUSES.map((s) => ({ value: s, label: s })),
      value: filterValue(params, "status"),
      onChange: (v) => write((p) => withFilter(p, "status", v)),
      match: (v, value) => v.status === value,
    },
  ];

  return (
    <>
      <DataTable
        errorTitle="Couldn't load vendors"
        caption="Vendors, with their intake channel, API credentials, lifetime ticket volume and status"
        data={vendors}
        columns={columns}
        getRowId={(v) => v.id}
        isLoading={isLoading}
        error={error}
        onRetry={onRetry}
        search={{
          placeholder: "Search vendors by name…",
          value: params.search ?? "",
          onChange: (v) => write((p) => withSearch(p, v)),
        }}
        filters={filters}
        server={{ meta, params, onParams }}
        toolbarActions={toolbarActions}
        minWidth="51.25rem"
        emptyTitle="No vendors yet"
        emptyDescription="Vendors appear here with their intake channel and lifetime ticket volume."
        filteredEmptyTitle="No vendors match those filters"
        filteredEmptyDescription="Try a different intake channel or status, or clear the search."
      />

      {/* One dialog for the whole table — the row that opened it supplies the
          record, so there is no per-row popup mounted behind every button. */}
      <VendorFormDialog
        open={open}
        onOpenChange={setOpen}
        vendor={managed ?? undefined}
      />
    </>
  );
}
