"""Global login identity. One email = one person = one fixed role.

A user belongs to zero+ companies via `membership`. Superadmin has role
'superadmin' and no memberships. Role is immutable after creation.
"""

import uuid

from sqlalchemy import Boolean, ForeignKey, Index, String, Text, Uuid, text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base_class import Base
from app.db.mixins import AuditMixin, IdMixin, SoftDeleteMixin


class User(Base, IdMixin, AuditMixin, SoftDeleteMixin):
    __tablename__ = "users"

    #: Both NULLABLE, because a technician has neither: their phone is the
    #: credential and they sign in with an OTP. Console users have both.
    #:
    #: The model said `nullable=False` until the schema was squashed, while a
    #: later migration had quietly made the columns nullable — so the models and
    #: the database disagreed, and only the migration was right. Anything
    #: generated from the models would have made technicians impossible to
    #: create.
    email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    password_hash: Mapped[str | None] = mapped_column(Text, nullable=True)
    full_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    phone: Mapped[str | None] = mapped_column(String(32), nullable=True)

    role: Mapped[str] = mapped_column(
        String(32), ForeignKey("roles.key", ondelete="RESTRICT"), nullable=False
    )
    # Populated for non-admin/superadmin roles; NULL otherwise.
    profile_image_url: Mapped[str | None] = mapped_column(Text, nullable=True)

    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    # Remembers the last company the user worked in (switcher default).
    # FK added via ALTER in the migration (companies is created alongside users).
    last_active_company_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )

    # NB: the case-insensitive UNIQUE index on lower(email) is created in the
    # migration (functional indexes aren't reliably autogenerated).
    __table_args__ = (
        Index("ix_users_role", "role"),
        # Covers the FK above. Deleting a company would otherwise scan every
        # user on the platform to find whose "last active" pointer to clear.
        Index("ix_users_last_active_company", "last_active_company_id"),
    )
