import { cn } from "@/lib/utils";
import type { SlaState, TicketStatus } from "@/types";

/**
 * Static class strings, one per status. An interpolated `bg-status-${slug}`
 * would never be generated by Tailwind and would render transparent.
 */
const STATUS_CLASS: Record<TicketStatus, string> = {
  New: "bg-status-new-bg text-status-new",
  "Slot Pending": "bg-status-slot-pending-bg text-status-slot-pending",
  Assigned: "bg-status-assigned-bg text-status-assigned",
  "In Progress": "bg-status-in-progress-bg text-status-in-progress",
  "AI Review": "bg-status-ai-review-bg text-status-ai-review",
  Escalated: "bg-status-escalated-bg text-status-escalated",
  Closed: "bg-status-closed-bg text-status-closed",
  "Force-Closed": "bg-status-force-closed-bg text-status-force-closed",
  Cancelled: "bg-status-cancelled-bg text-status-cancelled",
};

export function StatusBadge({ status }: { status: TicketStatus }) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold whitespace-nowrap",
        STATUS_CLASS[status]
      )}
    >
      {status}
    </span>
  );
}

const SLA_LABEL: Record<SlaState, string> = {
  ok: "On track",
  warn: "Due soon",
  breach: "Breached",
  done: "Met",
};

const SLA_CLASS: Record<SlaState, string> = {
  ok: "text-sla-ok",
  warn: "text-sla-warn",
  breach: "text-sla-breach",
  done: "text-sla-done",
};

/** Carries a word, not just a tint — colour alone fails WCAG 1.4.1. */
export function SlaBadge({ state }: { state: SlaState }) {
  return (
    <span
      className={cn(
        "text-xs font-semibold whitespace-nowrap",
        SLA_CLASS[state]
      )}
    >
      {SLA_LABEL[state]}
    </span>
  );
}
