import { cn } from "@/lib/utils";
import { APPROVAL_LABELS, type ApprovalStatus } from "@/types/approval";
import type { SlaState, TicketStatus } from "@/types";

/**
 * Static class strings, one per status. An interpolated `bg-status-${slug}`
 * would never be generated by Tailwind and would render transparent.
 */
const STATUS_CLASS: Record<TicketStatus, string> = {
  New: "bg-status-new-bg text-status-new",
  "Slot Pending": "bg-status-slot-pending-bg text-status-slot-pending",
  Assigned: "bg-status-assigned-bg text-status-assigned",
  "In Progress": "bg-status-in-progress-bg text-status-in-progress",
  "Awaiting Customer": "bg-status-awaiting-customer-bg text-status-awaiting-customer",
  "AI Review": "bg-status-ai-review-bg text-status-ai-review",
  Escalated: "bg-status-escalated-bg text-status-escalated",
  Closed: "bg-status-closed-bg text-status-closed",
  "Force-Closed": "bg-status-force-closed-bg text-status-force-closed",
  Cancelled: "bg-status-cancelled-bg text-status-cancelled",
};

export function StatusBadge({ status }: { status: TicketStatus }) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold whitespace-nowrap",
        STATUS_CLASS[status]
      )}
    >
      {status}
    </span>
  );
}

const SLA_LABEL: Record<SlaState, string> = {
  ok: "On track",
  warn: "Due soon",
  breach: "Breached",
  done: "Met",
};

const SLA_CLASS: Record<SlaState, string> = {
  ok: "text-sla-ok",
  warn: "text-sla-warn",
  breach: "text-sla-breach",
  done: "text-sla-done",
};

/** Carries a word, not just a tint — colour alone fails WCAG 1.4.1. */
export function SlaBadge({ state }: { state: SlaState }) {
  return (
    <span
      className={cn(
        "text-xs font-semibold whitespace-nowrap",
        SLA_CLASS[state]
      )}
    >
      {SLA_LABEL[state]}
    </span>
  );
}

/**
 * Where a vendor-submitted product sits. Static strings, like `STATUS_CLASS`.
 *
 * In `shared/` on TWO consumers, which the tier rule normally reads as a
 * coincidence. The exception is that the two are in different SLICES —
 * `approvals/ApprovalTable` and `masters/CategoryTree` — so neither can own it
 * without the other importing a private folder. The rule is about promoting too
 * early out of one slice; this was never in one.
 *
 * Rejected is `warn`, not `danger`. `danger` is spoken for by escalation,
 * no-show and serial mismatch — the three rows about a customer who has already
 * been let down. A rejected product is a task with a fix, which is what `warn`
 * already means here for force-close and an expired invite.
 */
const APPROVAL_CLASS: Record<ApprovalStatus, string> = {
  pending: "bg-info-bg text-info",
  approved: "bg-ok-bg text-ok",
  rejected: "bg-warn-bg text-warn",
};

export function ApprovalBadge({
  status,
  className,
}: {
  status: ApprovalStatus;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-semibold whitespace-nowrap",
        APPROVAL_CLASS[status],
        className
      )}
    >
      {APPROVAL_LABELS[status]}
    </span>
  );
}
